### ISSUE TITLE
Gitsings colors are almost indistinguishable

### ISSUE THREAD

**Issue by MaxVerevkin** [ellisonleao/gruvbox.nvim#106]
Currently, green color is used for "Add" and aqua for "Change". My issue is that they are very similar and it's not obvious what is what:

![image](https://user-images.githubusercontent.com/34583604/158880842-95aa09d7-6eba-46dd-9f61-861cffc3c901.png)

I propose using aqua for "Add" and orange for "Change":

![image](https://user-images.githubusercontent.com/34583604/158881145-a99abd92-4c68-46d2-9cb2-32bfe04d2bf1.png)

**Comment by ellisonleao** [comment]
hey @MaxVerevkin have you compared with the original community version to see if the bug is also happening there?

**Comment by MaxVerevkin** [comment]
hi @ellisonleao, yes the original uses the same colors. Should this proposal first be accepted by "upstream"?

**Comment by ellisonleao** [comment]
@MaxVerevkin yep, we are trying to keep the same colors here. I have access to the original community project, you can open an issue over there and we can discuss it. What do you think?

**Comment by MaxVerevkin** [comment]
Sure.

**Comment by CleoMenezesJr** [comment]
I have exactly the same problem. I believe the upstream color choice was not the best. I'll see if anyone has opened a similar ticket there.
![image](https://user-images.githubusercontent.com/54215258/163052552-8b46b686-dc3d-42b0-84f3-3290dbd3d7fa.png)

**Comment by ellisonleao** [comment]
@MaxVerevkin going back to this issue, i believe we can make the change to orange now and if we have more complaints we can discuss a better color. Can you please open a PR with that change please?

**Comment by MaxVerevkin** [comment]
@ellisonleao sure, in which repo?

**Comment by ellisonleao** [comment]
this one. Then we can suggest to the main one. Makes sense?
