### ISSUE TITLE
Search highlighting looks wrong after latest commit

### ISSUE THREAD

**Issue by hadeedji** [ellisonleao/gruvbox.nvim#110]
How it should look:
![expected](https://user-images.githubusercontent.com/5730404/163780984-6ff4a0cc-a68e-43a5-b3ca-bc442a296a89.png)

How it looks:
![observed](https://user-images.githubusercontent.com/5730404/163781004-ab18886c-d9fd-49e9-8419-f20cfd792b5c.png)

In addition to this, I also noticed bold text and italic comments not working.
All these issues are fixed by reverting to the previous commit. That's how I took the expected picture.

**Comment by YuvalHelman** [comment]
Seeing the same issue.
Unfortunately going over the recent commit diff I couldn't find the problem..
would appreciate if you can take a look @ellisonleao 

Thanks for your work!

**Comment by ellisonleao** [comment]
@hadeedji @YuvalHelman just pushed a change that fixed that. Can you pull latest and try again please?

**Comment by MaxVerevkin** [comment]
@ellisonleao fixes for me

**Comment by roland-rollo** [comment]
Fixed for me too.
