### ISSUE TITLE
Can't get LSP underline

### ISSUE THREAD

**Issue by eeeXun** [ellisonleao/gruvbox.nvim#111]
After the https://github.com/ellisonleao/gruvbox.nvim/commit/2103170eb9edb0aa90ee2a34f9fea16cc5690cd5 update, I can't get the underline of LSP.
LSP config like this
```lua
vim.diagnostic.config({
    underline = true,
})

```

**Comment by ellisonleao** [comment]
@eeeXun I've just pushed a change that could possibly fix that issue. Can you pull latest and try again, please?

**Comment by eeeXun** [comment]
Fixed. Thank you👍
