### ISSUE TITLE
Please consider using releases

### ISSUE THREAD

**Issue by kkremitzki** [ellisonleao/gruvbox.nvim#115]
Hello, I notice you've bumped the dependencies for this colorscheme to neovim 0.7 which was quite recently released. I haven't updated yet, so this dependency bump has broken my setup, and because there are no releases for this project, I can't pin a dependency on an old version which would continue to work. Could you please consider using releases to avoid this problem?

**Comment by sstark** [comment]
Releases are so last century :)

I work around that problem by adding a local tag to `~/.config/nvim/plugged/gruvbox.nvim:`

    git checkout dc6bae9
    git tag my06

Then in init.vim I use

    Plug 'ellisonleao/gruvbox.nvim', { 'tag': 'my06' }

Still not perfect having to do that, but it works.

**Comment by darkangel-ua** [comment]
You don't need local tags for that - just use `commit` key. Both `Plug` and `packer` support that.

**Comment by sstark** [comment]
missed that -- thanks!

**Comment by ellisonleao** [comment]
Hey @kkremitzki and others, thanks for the advice. I've opened #116 to talk about breaking changes. In the meantime, is it too hard to update to the latest neovim now? Or else you can use use the `commit` flag in your favorite plugin manager. How's that sound?

**Comment by sstark** [comment]
For Arch etc. no problem. Ubuntu users are still on 0.6 if they use `https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable` and are not willing to switch to the unstable ppa. Even Debian unstable has not updated yet.

**Comment by im-n1** [comment]
@sstark 
> Releases are so last century :)

Releases are the base cable. If you work in a software field where A depends on B releases are the one and only thing in terms of dependency-based-world that keeps it together.

Feel free to argue with kernel developers if you think different.
