### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/gruvbox.nvim#116]
We will be using this issue to talk about breaking issues for this repo

**Comment by ellisonleao** [comment]
New configuration system:

- All the `vim.g.gruvbox_*` vars are now replaced in a new configuration system using a Lua function. Please check the configuration section in the [README](https://github.com/ellisonleao/gruvbox.nvim#configuration) file for how to set up your custom colors. 
- Improved configurations are removed (`gruvbox_improved_strings`, `gruvbox_improved_warnings`)
- Highlight group overrides can be done in the setup process via the new `overrides` table

**Comment by ngalaiko** [comment]
hi! I've just experienced the breaking change and found this issue

could you please consider using some kind of alerting when such changes occur?

for instance, I think it would be great if on startup, I could see a message in vim saying that a plugin has deprecated / fully-removed a flag, so I don't need to track it down myself

**Comment by lucax88x** [comment]
Another breaking change is that gruvbox.colors was renamed to gruvbox.palette

**Comment by ellisonleao** [comment]
Moving this to discussions https://github.com/ellisonleao/gruvbox.nvim/discussions/133
