### ISSUE TITLE
No transparancy for SignColumn

### ISSUE THREAD

**Issue by ch3rr1** [ellisonleao/gruvbox.nvim#120]
When trying to set the SignColumn transparent with `g:gruvbox_sign_column = "none"` it doesn't recognize `none` as an available color. Can this be added please?

**Comment by ellisonleao** [comment]
Highlight group overrides will be added in #96

**Comment by arminveres** [comment]
> When trying to set the SignColumn transparent with `g:gruvbox_sign_column = "none"` it doesn't recognize `none` as an available color. Can this be added please?

I set it to 'bg0' an now it's transparent, you could try that for the time being.

**Comment by ellisonleao** [comment]
hey guys, the new configuration system is up. Can you try to override the `SignColumn` for your needs and check if its working properly please?

**Comment by ch3rr1** [comment]
Hey @ellisonleao, thanks a lot for the update - works for me now!
