### ISSUE TITLE
`TSNamespace` is inverted?

### ISSUE THREAD

**Issue by MaxVerevkin** [ellisonleao/gruvbox.nvim#121]
This is what I mean:

![image](https://user-images.githubusercontent.com/34583604/174743708-b523b5ab-15b1-43d7-a12f-9e000b4f482f.png)

It looks like foreground and background of "crate" are swapped? Please correct me if this is intended.

**Comment by ellisonleao** [comment]
@MaxVerevkin the color for error should be red now in the bg.
![Screenshot from 2022-06-29 15-18-01](https://user-images.githubusercontent.com/178641/176507860-975b7bed-cbad-4db1-9488-aab9d32fe426.png)
 
Can you check again and close if it's okay? thanks!

**Comment by MaxVerevkin** [comment]
The regex highlighter parses `crate::` as an error (even though it is not). Tree sitter says it's `TSNamespace`. I checked the latest master changes, and it seems to be highlighted correctly (just like `util::`). Thanks!
