### ISSUE TITLE
new config options

### ISSUE THREAD

**Issue by andy941** [ellisonleao/gruvbox.nvim#125]
**Is your feature request related to a problem? Please describe.**
I like the port  lot, I think is well made. I am only missing some customization options on what's italic, bold etc.

**Describe the solution you'd like**
The new configuration options (more lua-like) are a godsend, thank you for that. I think it would be even better if the customization could be more similar to colorschemes like nightfox:
``` lua
styles = {              -- Style to be applied to different syntax groups
 comments = "italic", -- change style of comments to be italic
  keywords = "bold", -- change style of keywords to be bold
  functions = "bold, italic", -- styles can be a comma separated list
  numbers = "NONE",
  strings = "NONE",
   types = "NONE",
   variables = "NONE",
 }
```
I for example don't like the strings to be in italic, but I'd like to have that for comments and functions. Is this possible/too much work to implement such a config option? I would really like that easy, fine grain tuning.

**Describe alternatives you've considered**
It might be possible with some lua configuration outside of the colorscheme, I am open to resort to that but I can't figure out how to do it.

Thank you again for the plugin, it works beautifully with treesitter.

Andrea

**Comment by ellisonleao** [comment]
hey @andy941 thanks for the issue. We will discuss fine grained improvements later on. for now i would keep this way and just try to make the changes for some groups using the `overrides` table. Would that work for now?

**Comment by andy941** [comment]
Sure, I would be happy with that as well, whatever fits. I'll look into it tomorrow (I am still learning neovim). You can close the issue if you like. 
P. S. : has gruvbox_transparent_background=1 been migrated to the new config system? 
Thanks for the prompt reply!

**Comment by ellisonleao** [comment]
No, that config never existed since the initial port
