### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by NOTMASTER09** [ellisonleao/gruvbox.nvim#126]
**Is your feature request related to a problem? Please describe.**
New configuration system has nothing equivalent to setting g:gruvbox_transparent_bg to 1

**Describe the solution you'd like**
Add a new config option

**Describe alternatives you've considered**
I could try to override every highlight group, but that's a hack

**Additional context**
None

**Comment by ellisonleao** [comment]
What terminal do you use? isn't just better to add transparency over there?

**Comment by NOTMASTER09** [comment]
The problem is that transparency dissapears once i run nvim, because of termguicolor

**Comment by Sife-ops** [comment]
> Honestly, I don't really like the transparency behavior. I can see that the original implementation is removed in the main gruvbox project, so I am not even sure if that is supported anymore. What if you just override the `Normal` group in your config. Will that work?
> 
> ```lua
> require("gruvbox").setup({
>    overrides = {
>        Normal = {},
>    }
> })
> vim.cmd("colorscheme gruvbox")
> ```

I tried this but it didn't work.

**Comment by eeeXun** [comment]
https://github.com/ellisonleao/gruvbox.nvim/issues/107#issuecomment-1101352293

You need to set `guibg` and `ctermbg` of `Normal` to NONE after `colorscheme gruvbox`
```lua
vim.cmd("colorscheme gruvbox")
vim.api.nvim_set_hl(0, "Normal", {guibg = NONE; ctermbg = NONE})
```

**Comment by ellisonleao** [comment]
Closing this since i am not trying to add support for this right now
