### ISSUE TITLE
'inverse' option in config object is not documented

### ISSUE THREAD

**Issue by andrewferrier** [ellisonleao/gruvbox.nvim#127]
The `config.inverse` option is used extensively through the definitions in `groups.lua`. Some of the new visuals were quite jarring for me (`Search`, `IncSearch`, `StatusLine`, etc.) as it turns out that this defaults to `false`. I can override it in `setup()` but that option is not documented in `README.md` - I had to read the code to figure it out.

**Comment by ellisonleao** [comment]
nice catch. Fixing it.
