### ISSUE TITLE
Problem with changing DiagnosticSign background color

### ISSUE THREAD

**Issue by Hxyspace** [ellisonleao/gruvbox.nvim#138]
**Describe the bug**
When I modify the DiagnosticSign background color, the DiagnosticSign foreground color is wrong

**To Reproduce**
```lua
require("gruvbox").setup({
    overrides = {
        DiagnosticSignInfo = { bg = "NONE" },
        DiagnosticSignHint = { bg = "NONE" },
        DiagnosticSignWarn = { bg = "NONE" },
        DiagnosticSignError = { bg = "NONE" },
    }
})
```

**Expected behavior**
Modify only the background color without changing the foreground color

**Screenshots**
before：
![image](https://user-images.githubusercontent.com/43908359/182547375-4abc14c1-1a42-491d-9c28-7d2c5313cca7.png)

after：
![image](https://user-images.githubusercontent.com/43908359/182547658-8a25d0b1-334f-4f96-aba6-e9eedb4200c0.png)

**Additional context**

**Comment by rReyvn** [comment]
Have the same problem, and i manage to fix by change this

```
require('gruvbox').setup({
  overrides = {
    SignColumn = { bg = "NONE" },
    GruvboxRedSign = { bg = "NONE" },
    GruvboxYellowSign = { bg = "NONE" },
    GruvboxBlueSign = { bg = "NONE" },
    GruvboxAquaSign = { bg = "NONE" },
  }
})
```

**Comment by Hxyspace** [comment]
@rReyvn Thanks for your reply, it worked for me

> Have the same problem but manage to fix by change this
> 
> ```lua
> require('gruvbox').setup({
>   overrides = {
>     SignColumn = { bg = "NONE" },
>     GruvboxRedSign = { bg = "NONE" },
>     GruvboxYellowSign = { bg = "NONE" },
>     GruvboxBlueSign = { bg = "NONE" },
>     GruvboxAquaSign = { bg = "NONE" },
>   }
> })
> ```
