### ISSUE TITLE
Conflict with gruvbox-flat

### ISSUE THREAD

**Issue by wgxh-cli** [ellisonleao/gruvbox.nvim#139]
**Describe the bug**
Failed to call `colorscheme gruvbox`.

**To Reproduce**
1. Install this plugin and `gruvbox-flat.nvim`.
2. Use `colorscheme gruvbox` to set the current theme.
3. See the error.

**Expected behavior**
It should work normally.

**Screenshots**
For some reason, I cannot upload the screenshots. But I could describe the error information.
It seems like this:

> Attempt to call `gruvbox.load` which is a nil value
> ...

**Possible way to fix**
It should be a module name conflict, maybe `gruvbox-flat.nvim` used the same module name to this.
When I removed `gruvbox-flat.nvim`, this works normally.

Please fix this! Thanks!

**Comment by wgxh-cli** [comment]
BTW, [here](https://github.com/eddyekofo94/gruvbox-flat.nvim) is the repository of `gruvbox-flat.nvim`.

**Comment by ellisonleao** [comment]
hey @wgxh-cli , unfortunately, you can only use one of them since they all share the same color name and Lua namespace
