### ISSUE TITLE
having darker popups

### ISSUE THREAD

**Issue by mohammadne** [ellisonleao/gruvbox.nvim#142]
**Is your feature request related to a problem? Please describe.**
is there any way to have a draker sidebars like for `NvimTree`?
I have tested different setups but I couldn't make it work. (the contrast option has no change)

**Describe the solution you'd like**
add an option to have darker popups.

**Comment by ellisonleao** [comment]
hey @mohammadne can you give more details on what are the expectations? Also, can you share some configs you've tried please?

**Comment by ellisonleao** [comment]
closing due to no more feedback
