### ISSUE TITLE
Add nvim-tree group hl

### ISSUE THREAD

**Issue by mario-amazing** [ellisonleao/gruvbox.nvim#147]
It will be awesome to add nvim-tree group support: 
My proposal is:
```lua
    -- nvim-tree
    NvimTreeSymlink = { link = "GruvboxBlue" },
    NvimTreeFolderName = { link = "GruvboxGreen" },
    NvimTreeRootFolder = { link = "GruvboxPurple" },
    NvimTreeFolderIcon = { link = "GruvboxOrange" },
    NvimTreeExecFile = { link = "GruvboxYellow" },
    NvimTreeSpecialFile = { link = "GruvboxFg1" },
    NvimTreeIndentMarker = { link = "GruvboxGray" },

```

**Comment by ellisonleao** [comment]
hey @mario-amazing thanks for the issue. Are the current highlights from nvim-tree have some links already? I can't tell because i don't use this plugin

**Comment by mario-amazing** [comment]
@ellisonleao, Yes, right here https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L1283
And I've already configured it (config above)
<img width="281" alt="image" src="https://user-images.githubusercontent.com/9537753/186545275-0d932a71-591a-4c9c-9be8-9d0f18028ac5.png">
So could you add it or maybe I'll create MR for it?

**Comment by Diaoul** [comment]
I've done my own theme following `exa`'s gruvbox style.
Nvim Tree:
![image](https://user-images.githubusercontent.com/319220/190922052-f5cac292-64dd-4943-85f1-35d00be339ed.png)
Exa:
![image](https://user-images.githubusercontent.com/319220/190922089-75836bf7-e7fa-4cd7-9ec9-85404606bdba.png)

**Comment by ellisonleao** [comment]
@Diaoul i've liked this one. Would you be able to send a PR with that addition?
