### ISSUE TITLE
Treesitter support!

### ISSUE THREAD

**Issue by Diaoul** [ellisonleao/gruvbox.nvim#154]
**Is your feature request related to a problem? Please describe.**
The theme is great but it would be better and more coherent with a treesitter tighter integration.
And who uses neovim without treesitter anyways nowadays? :sweat_smile: 

**Describe the solution you'd like**
Integration to treesitter much like [catppuccin](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/treesitter.lua)

**Describe alternatives you've considered**
Roll with the default

**Additional context**
Here is a screenshot of Python under various themes:
- gruvbox-material
- gruvbox (this one)
- catppuccin
- gruvbox-baby

For example we can notice that:
- all the other themes use the same color for class than from includes (and it looks better IMO)
- there is an overuse of orange in this one (I would probably tune down dots and brackets to fg2 or fg3)
- bold green for function names and bold orange for builtins are a bit too much "in-your-face" IMO (maybe I'm just not into bold/italic that much)
![image](https://user-images.githubusercontent.com/319220/192961022-834e073e-8f49-4333-99fd-63843dc2e673.png)

**Comment by ellisonleao** [comment]
Treesitter support is using the current links from the original version. If the current groups are not working for you, you can always override the groups in the setup call. For the treesitter hlmap I don't think we will support that for now

**Comment by ellisonleao** [comment]
closing this since new group support was added in the latest versions. feel free to reopen if the issue still remains
