### ISSUE TITLE
Diff mode selections are barely visible when selected text with differences

### ISSUE THREAD

**Issue by sid-6581** [ellisonleao/gruvbox.nvim#156]
**Describe the bug**
When in diff mode, selections are barely visible on text where there is a difference.

The background remains the same, and only the foreground color changes. The difference is so minimal that it is almost impossible to see.

Text that is the same between the two files, with no diff highlighting, is highlighted as normal when selected.

**To Reproduce**

Diff two files and try to select text where there is a difference.

**Expected behavior**
Expect the background to change to make it more apparent which text is selected.

**Screenshots**

No selection:

![image](https://user-images.githubusercontent.com/28602336/193829808-dc8bbc70-e50f-4efd-b966-12994e0b6012.png)

With selection:

![image](https://user-images.githubusercontent.com/28602336/193829876-75837a8e-7f56-4a06-9945-bc0a56b715db.png)

**Additional context**

I tried adding `invert_selection = true` in setup, but that didn't change anything in diff mode.

**Comment by LucasTavaresA** [comment]
you have to set `inverse = true`

**Comment by sid-6581** [comment]
`inverse = true` is already the default, and I haven't overridden it. It's not working.

**Comment by LucasTavaresA** [comment]
oh its false my bad

**Comment by sid-6581** [comment]
I managed to get something decent looking using this:

```cs
    require("gruvbox").setup({
      contrast = "hard",
      inverse = false,
      overrides = {
        GruvboxAquaSign = { bg = "NONE" },
        GruvboxBlueSign = { bg = "NONE" },
        GruvboxGreenSign = { bg = "NONE" },
        GruvboxOrangeSign = { bg = "NONE" },
        GruvboxPurpleSign = { bg = "NONE" },
        GruvboxRedSign = { bg = "NONE" },
        GruvboxYellowSign = { bg = "NONE" },
        SignColumn = { bg = "NONE" },
        DiffDelete = { bg = colors.neutral_red, fg = colors.dark0 },
        DiffAdd = { bg = colors.neutral_green, fg = colors.dark0 },
        DiffChange = { bg = colors.neutral_aqua, fg = colors.dark0 },
        DiffText = { bg = colors.neutral_yellow, fg = colors.dark0 },
      },
    })
```

I tried not setting the foreground to keep the syntax highlighting, but I would have had to come up with some very dark or different background colors to not clash with the syntax highlighting. At least with these colors everything isn't super bright, and highlighting works in visual mode.

I'm also deleting the backgrounds for the signs and sign column since the background interfered with the cursorline in things like neo-tree, etc.
