### ISSUE TITLE
Support semantic tokens

### ISSUE THREAD

**Issue by polyzen** [ellisonleao/gruvbox.nvim#158]
https://github.com/theHamsta/nvim-semantic-tokens/blob/master/doc/nvim-semantic-tokens.txt
https://github.com/theHamsta/nvim-semantic-tokens/blob/master/lua/nvim-semantic-tokens/presets/default.lua

**Comment by nabaco** [comment]
Resurfacing this as https://github.com/neovim/neovim/pull/21100 was merged.

**Comment by SeniorMars** [comment]
added in #211
