### ISSUE TITLE
Treesitter highlighting is broken after updating treesitter

### ISSUE THREAD

**Issue by Holi0317** [ellisonleao/gruvbox.nvim#159]
**Describe the bug**

See https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f and https://github.com/nvim-treesitter/nvim-treesitter/pull/3656.

nvim-treesitter has removed `TS*` highlight group which breaks gruvbox.

Noticed this when editing HTML file as the highlighting for all tags are gone (see screenshot)

**To Reproduce**

1. Update to latest nvim-treesitter
2. Open a HTML file
3. The tags should have color, but not after the latest update

**Expected behavior**

The highlighting should be the same before update.

**Screenshots**

![image](https://user-images.githubusercontent.com/6838982/196091773-219d8bdd-1c1d-457d-9bea-1ed817ff9b0b.png)

Left: After updating nvim-treesitter. Right: Before the commit mentioned

**Additional context**

I am not very familiar with how (neo)vim's highlighting works so correct me if I am wrong ;p.

From a glance on the treesitter doc and some experimentation, seems the recommended way of doing highlighting is now adding highlight group according to `highlight.scm` directly. Which means adding `@tag` group for the HTML tags group.

I'd happy to make a PR for fixing this. But I am not sure which approach should I go for. Either:

1. Add rules and try to restore highlighting result before the update; or
2. Look into vscode's gruvbox theme and copy their rule on treesitter highlighting

Maybe relates to https://github.com/ellisonleao/gruvbox.nvim/issues/154?

**Comment by dahmc** [comment]
Some more details here: https://www.reddit.com/r/neovim/comments/y5rofg/recent_treesitter_update_borked_highlighting/

**Comment by suruaku** [comment]
This is not a fix, but if you use Packer to manger your plugins. Use [PackerSnapshot](https://github.com/wbthomason/packer.nvim#performing-plugin-management-operations) between updates. That way you can easily rollback to working snapshot. This is especially good use for treesitter since "Treesitter and nvim-treesitter highlighting are an experimental feature of Neovim."
