### ISSUE TITLE
Some elements have strange highlighting?

### ISSUE THREAD

**Issue by Integralist** [ellisonleao/gruvbox.nvim#160]
**Describe the bug**
I use https://github.com/folke/noice.nvim and have noticed that the Cmd/Search bar has a highlight behind it that isn't present in other colourschemes.

**To Reproduce**
No steps to reproduce, but if it's of any help my configuration can be found here:
https://github.com/Integralist/dotfiles/tree/main/.config/nvim 

**Expected behavior**
Not to have a lighter background highlight on this particular UI element.

**Screenshots**
Here is the gruvbox theme with a strange highlight:
<img width="773" alt="Screenshot 2022-10-19 at 09 16 21" src="https://user-images.githubusercontent.com/180050/196636097-1cda1766-604d-41ef-a011-3b817799db2a.png">

Here is another colourscheme ([falcon](https://github.com/fenetikm/falcon)) which doesn't have that highlight applied:
<img width="834" alt="Screenshot 2022-10-19 at 09 16 36" src="https://user-images.githubusercontent.com/180050/196636562-b43e64b9-3ac1-4abc-98ba-34f47360de05.png">

**Comment by Integralist** [comment]
For anyone else who needs to fix this, I got help from the neovim Reddit to point me at the relevant highlight groups that Noice uses. I opted to keep things simple and just use vimscript inside of Lua to setup the various autocommands etc

> **NOTE**: I found the right colours to use by first executing `:hi NoiceCmdline<...>` which typically would reveal it was linked to an LSP diagnostic highlight group (e.g. `DiagnosticSignInfo`). So I would then do the same thing again, `:hi DiagnosticSignInfo` which would then reveal it was linked to a gruvbox highlight group (e.g. `GruvboxYellowSign`) and so I'd run `:hi GruvboxYellowSign` and copy the `guifg` colour and when I came to override the settings (see below) I use that colour and just set `guibg` to none.

```lua
vim.cmd([[
  function! FixGruvboxForNoice() abort
    if g:colors_name == "gruvbox"
      highlight NoiceCmdlinePopupBorderCmdline guifg=#83a598 guibg=NONE
      highlight NoiceCmdlinePopupBorderFilter guifg=#83a598 guibg=NONE
      highlight NoiceCmdlinePopupBorderHelp guifg=#83a598 guibg=NONE
      highlight NoiceCmdlinePopupBorderInput guifg=#83a598 guibg=NONE
      highlight NoiceCmdlinePopupBorderLua guifg=#83a598 guibg=NONE
      highlight NoiceCmdlinePopupBorderSearch guifg=#fabd2f guibg=NONE

      highlight NoiceCmdlineIconCmdline guifg=#83a598 guibg=NONE
      highlight NoiceCmdlineIconFilter guifg=#83a598 guibg=NONE
      highlight NoiceCmdlineIconHelp guifg=#83a598 guibg=NONE
      highlight NoiceCmdlineIconInput guifg=#83a598 guibg=NONE
      highlight NoiceCmdlineIconLua guifg=#83a598 guibg=NONE
      highlight NoiceCmdlineIconSearch guifg=#fabd2f guibg=NONE
    endif
  endfunction

  augroup ApplyFixGruvboxForNoice
    autocmd!
    autocmd ColorScheme * call FixGruvboxForNoice()
  augroup END

  silent !rm $VIMRUNTIME/colors/*.vim &> /dev/null
  set background=dark
  colorscheme gruvbox
  highlight link GitSignsChange GruvboxYellowSign
]])
```

**Comment by stepanzak** [comment]
Hi, I don't think this should be closed as completed, because @Integralist 's solution is just a workaround and the wrong background on noice.nvim is still and issue.
