### ISSUE TITLE
Colorscheme appears to mess up width of ➜ character

### ISSUE THREAD

**Issue by samjwill** [ellisonleao/gruvbox.nvim#161]
## Describe the bug

This arrow character's (➜) size appears to somehow be affected by this colorscheme. It is used by https://github.com/folke/which-key.nvim as [the default separator](https://github.com/folke/which-key.nvim/blob/45be0efb121415abdf9975734fc566855b1fa2e8/doc/which-key.txt#L144), which is why I noticed it, as it borks the UI if you don't set it up to use another character or colorscheme.
![image](https://user-images.githubusercontent.com/25990267/196794555-857906d4-d5e1-4fcf-aa19-27d71c95c169.png)  This issue persists regardless of font used, and is not present with other colorschemes I've tried.

## To Reproduce

1. Install the gruvbox.nvim colorscheme and set the colorscheme for the Neovim session to it.
2. Open a buffer.
3. Insert the "➜" character.
4. In a comment, it's ~twice as wide as other characters. 
![image](https://user-images.githubusercontent.com/25990267/196795458-85be1d5f-dd55-4c34-b05d-8fbf3de737e1.png)
    Cursor for reference:
![image](https://user-images.githubusercontent.com/25990267/196795546-62d66ca1-c566-4e32-a4f1-6c5ef01a5061.png)
![image](https://user-images.githubusercontent.com/25990267/196795597-6451b006-0be4-417d-819e-04fb9833b3b8.png)
    Occasionally, it will completely cover the character that comes directly after it. E.g.) There's a hidden `"` after the arrow here:
![image](https://user-images.githubusercontent.com/25990267/196798101-b249e58b-7857-48b6-a1da-85361f3e6068.png)
    Highlighted with the cursor so that you can see the hidden `"`:
![image](https://user-images.githubusercontent.com/25990267/196798184-e857b5a9-3e85-4385-b507-856ed35877f3.png)
5. If the line is uncommented, the character is significantly smaller, and fits in the expected bounds for a single character. 
![image](https://user-images.githubusercontent.com/25990267/196795683-0829f377-8f0f-4149-9bd0-7f44207cd066.png)

## Expected behavior

As with most other colorschemes (e.g. the default `slate` colorscheme that ships with Neovim), the character does not spill over into the space for the next character, regardless of whether it's commented out or not.
![image](https://user-images.githubusercontent.com/25990267/196796994-99b37637-9df1-4146-94a5-87ca3f09c3a1.png)

How https://github.com/folke/which-key.nvim is supposed to look:
![image](https://user-images.githubusercontent.com/25990267/196797385-94fffda7-4b57-4255-9666-090984df8f3c.png)

## Additional context

Note that this ➜ is not the same as the probably more common → character.

If this isn't an issue related to this plugin, I apologize. I figure it is because as soon as I set the colorscheme to something else, it behaves fine, and the issue persists with gruvbox regardless of which font I use.

**Comment by ellisonleao** [comment]
@samjwill what terminal are you using? I am using wezterm here and I can't reproduce the behaviour. Some images:

Light mode:

![Screenshot from 2022-11-10 10-41-36](https://user-images.githubusercontent.com/178641/201107191-90c3fb7f-46cf-40ea-8fc6-48439416a250.png)

Dark mode:

![Screenshot from 2022-11-10 10-41-44](https://user-images.githubusercontent.com/178641/201107215-0f17b4a5-9624-4d76-9cba-5df1c07eb802.png)

Both color modes with the cursor inside the char also does not reflect your issue. Unfortunately there isn't much I can do here

**Comment by samjwill** [comment]
Hi! Here's some additional information. Looks like it might be related to something wrong on Konsole's end?

### Operating system/version

Kubuntu 22.04

### Terminal emulator/version

Konsole 21.12.3

### Neovim Version
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

### Minimal init.lua to reproduce

I included the Packer bootstrapping boilerplate for convenience.

```
-- Automatically install Packer on startup.
local install_path = vim.fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    packer_bootstrap = vim.fn.system
    {
        'git',
        'clone',
        '--depth',
        '1',
        'https://github.com/wbthomason/packer.nvim',
        install_path
    }
    vim.cmd("packadd packer.nvim")
end

local packer = require("packer")
packer.startup(function(use)
    -- Packer needs to manage itself
    use 'wbthomason/packer.nvim'

    use "ellisonleao/gruvbox.nvim"
    -- not "morhetz/gruvbox"

    -- Automatically set up your configuration after cloning packer.nvim
    if packer_bootstrap then
        vim.api.nvim_create_autocmd("User", {
            pattern = "PackerComplete",
            callback = function() print("Installation is complete! Please restart Neovim.") end
        })
        require('packer').sync()
    end
end)

vim.cmd("colorscheme gruvbox")
```
Note that for this init.lua, Neovim will require restarting in order to set the colorscheme after Packer is bootstrapped.

I tested out the kitty terminal emulator and the issue does not occur there. Perhaps it is some kind of weird interaction between certain colorschemes and the Konsole terminal emulator? It's odd because if I swap out gruvbox.nvim for tokyonight, I'm actually still getting the same issue,
![image](https://user-images.githubusercontent.com/25990267/201149212-ba549a07-a3ca-46e7-88c7-4be58ee4689b.png)
 but if I set, say, `:colorscheme slate`, the issue is gone.
![image](https://user-images.githubusercontent.com/25990267/201149311-1de85eb2-d276-4e2e-9f2b-f44af82aba29.png)
It looks like this issue is more related to the terminal emulator than the colorscheme? I'm not sure really. Apologies for the potentially faux-bug-report. It appears to be out of scope for this repo.
