### ISSUE TITLE
Highlight for WinBar (Neovim 0.8+)

### ISSUE THREAD

**Issue by maxbrunet** [ellisonleao/gruvbox.nvim#162]
**Is your feature request related to a problem? Please describe.**

The new WinBar added in Neovim 0.8+ does not have Gruvbox colors yet.

**Describe the solution you'd like**

```diff
diff --git a/lua/gruvbox/groups.lua b/lua/gruvbox/groups.lua
index 756f0d2..2cfaf39 100644
--- a/lua/gruvbox/groups.lua
+++ b/lua/gruvbox/groups.lua
@@ -164,6 +164,8 @@ groups.setup = function()
     Underlined = { fg = colors.blue, underline = config.underline },
     StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
     StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
+    WinBar = { fg = "...", bg = "...", reverse = config.inverse },
+    WinBarNC = { fg = "...", bg = "...", reverse = config.inverse },
     VertSplit = { fg = colors.bg3, bg = colors.bg0 },
     WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
     Directory = { link = "GruvboxGreenBold" },

```

Seems easy enough, but I trust you have better judgement for the choice of colors.

Thank you for making this colorscheme and no hurry :slightly_smiling_face:

**Describe alternatives you've considered**

Could be set in local config with `vim.api.nvim_set_hl()`  

**Additional context**

* [`:help 'winbar'`](https://neovim.io/doc/user/options.html#'winbar')
* [`:help hl-WinBar`](https://neovim.io/doc/user/syntax.html#hl-WinBar)

**Comment by ellisonleao** [comment]
hey @maxbrunet honestly i don't have any suggestions for the winbar color for now, I think you can submit a PR with those changes and we can start discussing it, what do you think?

**Comment by maxbrunet** [comment]
Sure! I actually picked colors last week
