### ISSUE TITLE
HTML tags got white color

### ISSUE THREAD

**Issue by Shrimp22** [ellisonleao/gruvbox.nvim#165]
Have a problem with svelte and HTML files 
Every HTML tag got white
Using nvim 0.8.0
![image](https://user-images.githubusercontent.com/86841678/198022793-bb6e1f47-6eb9-4fce-af35-d1f608fff4ed.png)

**Comment by ellisonleao** [comment]
hey @Shrimp22 can you pull latest and try again please?

**Comment by Shrimp22** [comment]
@ellisonleao It works now thank you so much!
