### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by Asheq** [ellisonleao/gruvbox.nvim#167]
**Describe the bug**
When loading nvim, I see:
```
Error detected while processing /home/ash/.vim/plugged/gruvbox.nvim/colors/gruvbox.lua:        
W18: Invalid character in group name                                                           
W18: Invalid character in group name                                                           
W18: Invalid character in group name                                                           
W18: Invalid character in group name                                                           
W18: Invalid character in group name                                                           
W18: Invalid character in group name                                                           
W18: Invalid character in group name```
```

**To Reproduce**
Open nvim

**Expected behavior**
No error

**Additional context**
```
:version                                                                                       
NVIM v0.7.0                                                                                    
Build type: RelWithDebInfo                                                                     
LuaJIT 2.1.0-beta3                                                                             
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMI
T -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstr
ict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing
-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsugges
t-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-s
trong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DN
VIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/
neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.de
ps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/run
ner/work/neovim/neovim/build/include                                                           
Compiled by runner@fv-az316-460                                                                
                                                                                               
Features: +acl +iconv +tui                                                                     
See ":help feature-compile"                                                                    
                                                                                               
   system vimrc file: "$VIM/sysinit.vim"                                                       
  fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"       
                                                                                               
Run :checkhealth for more info                                                                 
Press ENTER or type command to continue                 
```

**Comment by youkwhd** [comment]
i can confirm this, i have the same issue after updating the theme.

**Comment by floriankraft** [comment]
+1

**Comment by swysocki** [comment]
> **Describe the bug** When loading nvim, I see:
> 
> ```
> Error detected while processing /home/ash/.vim/plugged/gruvbox.nvim/colors/gruvbox.lua:        
> W18: Invalid character in group name                                                           
> W18: Invalid character in group name                                                           
> W18: Invalid character in group name                                                           
> W18: Invalid character in group name                                                           
> W18: Invalid character in group name                                                           
> W18: Invalid character in group name                                                           
> W18: Invalid character in group name```
> ```
> 
> **To Reproduce** Open nvim
> 
> **Expected behavior** No error
> 
> **Additional context**
> 
> ```
> :version                                                                                       
> NVIM v0.7.0                                                                                    
> Build type: RelWithDebInfo                                                                     
> LuaJIT 2.1.0-beta3                                                                             
> Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMI
> T -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstr
> ict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing
> -format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsugges
> t-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-s
> trong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DN
> VIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/
> neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.de
> ps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/run
> ner/work/neovim/neovim/build/include                                                           
> Compiled by runner@fv-az316-460                                                                
>                                                                                                
> Features: +acl +iconv +tui                                                                     
> See ":help feature-compile"                                                                    
>                                                                                                
>    system vimrc file: "$VIM/sysinit.vim"                                                       
>   fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"       
>                                                                                                
> Run :checkhealth for more info                                                                 
> Press ENTER or type command to continue                 
> ```

A Gruvbox prerequisite is  Neovim v0.8.0, it appears you are using v0.7.0.  Did you try upgrading?

**Comment by youkwhd** [comment]
> > **Describe the bug** When loading nvim, I see:
> > ```
> > Error detected while processing /home/ash/.vim/plugged/gruvbox.nvim/colors/gruvbox.lua:        
> > W18: Invalid character in group name                                                           
> > W18: Invalid character in group name                                                           
> > W18: Invalid character in group name                                                           
> > W18: Invalid character in group name                                                           
> > W18: Invalid character in group name                                                           
> > W18: Invalid character in group name                                                           
> > W18: Invalid character in group name```
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **To Reproduce** Open nvim
> > **Expected behavior** No error
> > **Additional context**
> > ```
> > :version                                                                                       
> > NVIM v0.7.0                                                                                    
> > Build type: RelWithDebInfo                                                                     
> > LuaJIT 2.1.0-beta3                                                                             
> > Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMI
> > T -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstr
> > ict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing
> > -format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsugges
> > t-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-s
> > trong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DN
> > VIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/
> > neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.de
> > ps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/run
> > ner/work/neovim/neovim/build/include                                                           
> > Compiled by runner@fv-az316-460                                                                
> >                                                                                                
> > Features: +acl +iconv +tui                                                                     
> > See ":help feature-compile"                                                                    
> >                                                                                                
> >    system vimrc file: "$VIM/sysinit.vim"                                                       
> >   fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"       
> >                                                                                                
> > Run :checkhealth for more info                                                                 
> > Press ENTER or type command to continue                 
> > ```
> 
> A Gruvbox prerequisite is Neovim v0.8.0, it appears you are using v0.7.0. Did you try upgrading?

I have neovim 0.8 installed, the issue still occurs.

```
NVIM v0.8.0-dev+92-g039d60bd9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
I think the issue is linked with commit https://github.com/ellisonleao/gruvbox.nvim/commit/2fc4980dfa17e76f7c7e963caa69599051d2e75e since the error says it all.

**Comment by floriankraft** [comment]
I can confirm that going back one commit works. I am using packer as a plugin manager and this solves it for me:

```lua
  use { 'ellisonleao/gruvbox.nvim', commit = 'cb7a8a867cfaa7f0e8ded57eb931da88635e7007' }
```

**Comment by Asheq** [comment]
> A Gruvbox prerequisite is Neovim v0.8.0, it appears you are using v0.7.0. Did you try upgrading?

Thanks @swysocki. I didn't realize the required version changed. I upgraded to the latest nvim Linux AppImage (`NVIM v0.8.0-1210-gd367ed9b2`) and the errors disappeared.

I'll leave this issue open for @ellisonleao to decide what to do with it. Perhaps the plugin should detect the version of neovim and print an error asking the user to upgrade if necessary.

**Comment by ellisonleao** [comment]
we put all the breaking changes here https://github.com/ellisonleao/gruvbox.nvim/discussions/133 . Please make sure to follow it. It is also a good idea to keep you neovim up with the stable version
