### ISSUE TITLE
Colors don't look good in in nvim-treesitter-context area

### ISSUE THREAD

**Issue by hovnatan** [ellisonleao/gruvbox.nvim#168]
I have https://github.com/nvim-treesitter/nvim-treesitter-context plugin installed which shows context of current function in top part of the window. Before the recent updates to gruvbox.nvim that area was highlighted uniformly but now there is some non-uniform highlighting that doesn't look good.

![Screenshot from 2022-10-28 11-33-37](https://user-images.githubusercontent.com/8426582/198530409-3b034297-4bdf-4522-bf42-22e0161fc13d.png) 

Can you please check if this is how it supposed to work from now on?

**Comment by yunag** [comment]
Try to add these lines of code to your gruvbox config.
```
overrides = {
    ["@variable"] = { bg = "NONE", fg = palette.fg1 },
    ["@text"] = { bg = "NONE", fg = palette.fg1 },
}
```

**Comment by hovnatan** [comment]
@yunag that didn't work. I ended up using `vim.cmd("hi link TreesitterContext Normal")`

**Comment by polyzen** [comment]
Probably should keep this open until a solution is implemented for everyone.
