### ISSUE TITLE
Treesitter highlighting doesn't seem to work

### ISSUE THREAD

**Issue by JwanKhalaf** [ellisonleao/gruvbox.nvim#170]
**Describe the bug**

Here is what I am currently getting when opening an AWS CDK (Go) file:

![image](https://user-images.githubusercontent.com/42877376/199697064-08317158-0d89-4172-a91d-820214b2cdd3.png)

**To Reproduce**

My config is [here.](https://github.com/JwanKhalaf/.dotfiles/tree/main/.config/nvim)

**Expected behavior**

With Treesitter, I expect good highlighting like I get in GoLand.

![image](https://user-images.githubusercontent.com/42877376/199697352-ff11715c-5b92-4cc9-9631-25ff530bf347.png)

I don't mean the colours should match, I mean the bits that are highlighted should be roughly the same so that the code is easier to digest.

**Comment by JwanKhalaf** [comment]
hmm, can you try with AWS CDK code please?

```
cdk init app --language go          
```

And then open the file containing the Stack code and send a screenshot?

Yours is looking so much nicer!

**Comment by JwanKhalaf** [comment]
By the way, all I have in terms of settings is:

```
vim.o.background = "dark"
command[[colorscheme gruvbox]]
```

Am I supposed to have this too?

![image](https://user-images.githubusercontent.com/42877376/201882476-0ac728fd-a064-4afb-8086-2131db04af00.png)

I assumed not, cause it states "Additional", meaning they're not mandatory!

**Comment by JwanKhalaf** [comment]
Here is the CDK code: https://gist.github.com/JwanKhalaf/5a3a5549feb5e88177447bb79bcb7364

**Comment by bamonroe** [comment]
I think I'm having a similar problem. I can't see many of the highlight groups defined [here](https://github.com/ellisonleao/gruvbox.nvim/blob/main/lua/gruvbox/groups.lua) when I use the `hl` command in nvim. In particular, for latex documents, the argument of `\textit{arg}` belongs to the highlight group "@text.emphasis", which should have the `italic` property. I can see this properly defined in the groups.lua file, but it just doesn't make its way into any file for me. If I manually type `lua vim.api.nvim_set_hl(0, "@text.emphasis", {italic = true})`, I get the correct italics, so I don't think there is something particularly wrong with my setup.

What's more, I added a "vim.pretty_print('hello')" [to this line](https://github.com/ellisonleao/gruvbox.nvim/blob/main/lua/gruvbox/init.lua#L44), and removed `colorscheme gruvbox` from my init.lua. So now  when I start nvim, I have the default colorscheme, but when I type `colorscheme gruvbox` I figure I should see `hello` in the messages, but I don't. So it looks to me like something isn't loading correctly. Happy to troubleshoot if it helps, I really enjoy the colorscheme.

**Comment by ellisonleao** [comment]
On my side i have the highlights:

![image](https://user-images.githubusercontent.com/178641/204300645-6c6f9dfa-1069-4acf-8b84-d4d9e06cc470.png)

**Comment by JwanKhalaf** [comment]
Man I jealous, I do not get that.

When you have that code open, if you run `:LspInfo` what do you see? I get:

![image](https://user-images.githubusercontent.com/42877376/204492187-ba4719ac-66dd-4e1c-a8dc-31fe13e1ad72.png)

**Comment by ellisonleao** [comment]
same thing.  For the sake of removing extra possibilities I would try to test this code in the stable version and check if the issue remains

**Comment by LucasTavaresA** [comment]
![print_30_14:26](https://user-images.githubusercontent.com/80704612/204866557-be16ad13-260d-4275-bb71-159cc047c9a1.png)

i also have something similar, you can test with `diff file1 file2 | nvim`, it goes normal when i disable treesitter highlighting

**Comment by JwanKhalaf** [comment]
I went ahead and install the stable release, and it still doesn't work :(

All my config is [on GitHub](https://github.com/JwanKhalaf/.dotfiles/tree/main/.config/nvim).

![image](https://user-images.githubusercontent.com/42877376/204918433-bd222cf8-9cde-4179-a357-d22042e3407d.png)

**Comment by JwanKhalaf** [comment]
Very good way to test things out! Nice one @bamonroe. If you do figure out what plugin is the cause, please let me know.

I'll also do some experiments from my end. Right now, I have the following plugins:

```
return require('packer').startup(function(use)
  -- allow packer (the plugin manager) to manage itself
  use 'wbthomason/packer.nvim'

  use 'ellisonleao/gruvbox.nvim'
  use 'itchyny/lightline.vim'
  use 'frazrepo/vim-rainbow'
  use 'nvim-lua/popup.nvim'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-telescope/telescope-fzy-native.nvim'
  use 'prettier/vim-prettier'
  use 'tpope/vim-surround'
  use 'tpope/vim-commentary'
  use 'christoomey/vim-system-copy'
  use 'mattn/emmet-vim'
  use 'neovim/nvim-lspconfig'
  use 'kyazdani42/nvim-web-devicons'
  use 'nvim-treesitter/nvim-treesitter'
  use 'hrsh7th/cmp-nvim-lua'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/nvim-cmp'
  use 'L3MON4D3/LuaSnip'
  use 'saadparwaiz1/cmp_luasnip'
end)
```

**Comment by bamonroe** [comment]
@JwanKhalaf I found that removing all the other color-schemes from my plugin config fixed the issue for me. Unfortunately I think you're best bet is to disable your plugins one at a time and see if it resolves the issue. Of the plugins you list above, I also use the following, so they seem unlikely to be the problem: 

```
  use 'wbthomason/packer.nvim'
  use 'ellisonleao/gruvbox.nvim'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'tpope/vim-surround'
  use 'neovim/nvim-lspconfig'
  use 'kyazdani42/nvim-web-devicons'
  use 'nvim-treesitter/nvim-treesitter'
  use 'hrsh7th/cmp-nvim-lua'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/nvim-cmp'
  use 'L3MON4D3/LuaSnip'
  use 'saadparwaiz1/cmp_luasnip'
```

**Comment by ellisonleao** [comment]
Yep, will close this since it's not likely to be an issue with the plugin
