### ISSUE TITLE
Error detected while processing /home/USER/.config/nvim/plugged/gruvbox.nvim/colors

### ISSUE THREAD

**Issue by bitboxer** [ellisonleao/gruvbox.nvim#171]
**Describe the bug**

After my latest `:PlugUpdate` I see this error when starting neovim:

```
Error detected while processing /home/USER/.config/nvim/plugged/gruvbox.nvim/colors/gruvbox.lua:
W18: Invalid character in group name
```

**To Reproduce**
1. Install the latest version of gruvbox.nvim
2. Start neovim

**Expected behavior**

No error during bootup

**Additional context**

neovim 0.7.2

**Comment by thopaw** [comment]
+1

**Comment by hongxuchen** [comment]
Same error here when I was using a kali-linux packed version of neovim (0.7). The issue was gone when I switched to https://github.com/neovim/neovim/releases/tag/v0.8.0 .

**Comment by pmyjavec** [comment]
I think this has to do with installing using "Plug" when this plugin seems designed to work with the newer "Pack" format.

**Comment by ellisonleao** [comment]
Guys, please update to the latest stable Neovim version ( 0.8+ ). That would fix the issue.
