### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by Yanis-F** [ellisonleao/gruvbox.nvim#175]
**Describe the bug**
A bunch of lua error are thrown on nvim startup

**To Reproduce**
With
```
➜ nvim -v
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org
```
with this init.lua
```lua
require('packer').startup(function(use)
	use  'ellisonleao/gruvbox.nvim'
end)

vim.cmd([[colorscheme gruvbox]])
```

open up nvim, you will see the errors

**Screenshots**
![image](https://user-images.githubusercontent.com/20617764/200725119-ab6387d5-4dda-4913-b1b6-220018ef2fdf.png)

**Comment by Yanis-F** [comment]
Commenting out these lines fix the warnings... 
probably need a better workaround though
https://github.com/ellisonleao/gruvbox.nvim/blob/9002dc7a717d38b7bbe212febe6370fd7d047308/lua/gruvbox/groups.lua#L249-L323

**Comment by ellisonleao** [comment]
@Yanis-F please update neovim to the latest stable version. This plugin does not support older versions anymore.
