### ISSUE TITLE
Breaking changes in nvim-treesitter cause wrong highlighting

### ISSUE THREAD

**Issue by timii** [ellisonleao/gruvbox.nvim#177]
**Describe the bug**
The `<template>` section in .vue files are currently being highlighted wrong, because of a breaking change to nvim-treesitter and the name of the highlight groups.

I coincidentally found out that a breaking change to names of highlight groups in nvim-treesitter probably cause this issue, by finding [this reddit thread](https://www.reddit.com/r/neovim/comments/yd4rfa/treesitter_stopped_working_for_template_section/) having the same issue as me. [One of the comments](https://www.reddit.com/r/neovim/comments/yd4rfa/comment/itq20eb/?utm_source=share&utm_medium=web2x&context=3) under that thread explained what maybe caused this issue.

[This](https://www.reddit.com/r/neovim/comments/yd4rfa/comment/itt66nf/?utm_source=share&utm_medium=web2x&context=3) other comment under the thread added a temporary fix that resolves the issue, until the theme is fixed. I will add a screenshot of the default highlighting without the fix and another screenshot with the temporary fix added.

**To Reproduce**
1. Open a .vue file with a `<template>`, `<style>` and `<script>` section
2. See wrong highlighting of `<template>` section

**Expected behavior**
Correct highlighting like in the `<script>` and `<style>` section

**Screenshots**
Current highlighting (without the fix):
![image](https://user-images.githubusercontent.com/56680452/201470891-7c9ca5b2-6870-49c8-b1f9-bf7f06ac8c10.png)

Highlighting after adding the temporary fix:
![image](https://user-images.githubusercontent.com/56680452/201471301-a3cb4f74-87f6-4848-be1e-13172c72ba71.png)

I don't know how easily this is fixable and if this is even a problem with this theme, but I just wanted to share what I found out, so it may help someone.

Any help is greatly appreciated!
Thanks

Other related reddit thread: https://www.reddit.com/r/neovim/comments/ytc9d8/a_psa_to_colourscheme_maintainers_please_support/

**Comment by ellisonleao** [comment]
We already support the new tree-sitter highlight groups [here](https://github.com/ellisonleao/gruvbox.nvim/blob/main/lua/gruvbox/groups.lua#L251-L325). Are we missing any groups? What neovim version are you using?

**Comment by timii** [comment]
Thanks for your response, interesting. My current neovim version is:
```bash
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
Then it's weird that the highlighting is wrong for me. Could it be a wrong neovim version or an older gruvbox version, or what else could the reason be?

**Comment by ellisonleao** [comment]
@timii can you try upgrading to latest stable (0.8.1) and trying again please?

**Comment by ellisonleao** [comment]
Closing since we've got no answer. Feel free to reopen if the issue remains
