### ISSUE TITLE
Highlighting issues running through docker

### ISSUE THREAD

**Issue by mmihira** [ellisonleao/gruvbox.nvim#185]
I'm running nvim through docker and getting some strange highlighting issues:

![image](https://user-images.githubusercontent.com/10894457/204206002-da0445dc-77d0-4525-8dba-bb620aab2419.png)

I'm not sure why the strings for example are highlighted like that ? It should only be the characters with the green
highlight but looks like it's the background ? 

Note: it works fine not running through docker. Would anyone know what the issue is ?

**Comment by IamGianluca** [comment]
Funny enough, I was going to open the same issue. Any idea what could be causing this? I'm using the same dotfiles in my machine and the Docker container.

![image](https://user-images.githubusercontent.com/4025968/204398947-0513699a-23f4-4951-86a6-fbe7bd50a0dd.png)

The top pane is inside the Docker container, and the one on the bottom is in the local environment.

**Comment by ellisonleao** [comment]
can you guys verify if you have 256 colors in the terminal? I am feeling that may be the issue

**Comment by IamGianluca** [comment]
Hi @ellisonleao, 

I just tried your suggestion and it did work! Thank you so much 🙏 

Specifically, I added this line to the Dockerfile:

```
ENV TERM screen-256color
```

**Comment by mmihira** [comment]
@ellisonleao @IamGianluca  Ahh thanks so much! That fixed the issue.

I'll close the issue now.
