### ISSUE TITLE
add airline support

### ISSUE THREAD

**Issue by marcoaaguiar** [ellisonleao/gruvbox.nvim#19]
With the original `morhetz/gruvbox`, the airline plugin "just works."
It would be nice to have it support the airline by default.

Useful link: https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim

**Comment by ellisonleao** [comment]
hey @marcoaaguiar thanks for raising the issue! Yes, multiple plugin support is still ongoing, i will be definitely adding that support ASAP

**Comment by NullSense** [comment]
Any updates on this?

**Comment by ellisonleao** [comment]
airline support is now enabled using the same vimscript as the main one, so you now can update your repos and use it.
