### ISSUE TITLE
Better JSX colors

### ISSUE THREAD

**Issue by afk-mario** [ellisonleao/gruvbox.nvim#197]
**Is your feature request related to a problem? Please describe.**
Currently Tree sitter colors for JSX are way worse than the supported JSX ones using `maxmellon/vim-jsx-pretty`

**Describe the solution you'd like**
Make the colors on JSX tree sitter similar to the ones using JSX-pretty

**Screenshots**

Using Tree sitter
![image](https://user-images.githubusercontent.com/1025751/213006931-7df0668a-a6df-4e76-854e-0059faab5679.png)

Using jsx-pretty

![image](https://user-images.githubusercontent.com/1025751/213007052-77bae059-4c2a-460e-b5fe-7bf0d7c90991.png)

**Comment by ellisonleao** [comment]
hey @afk-mario both options seem fine to me ( not a frontend dev here ). What do you think about overriding those groups for your personal need? Can you figure out how to get the groups and make the overrides?

**Comment by ellisonleao** [comment]
closing this since we didn't get any answer so far. Feel free to reopen

**Comment by Tyangs** [comment]
[gruvbox-baby](https://github.com/luisiacc/gruvbox-baby) has good support for treesitter jsx. I really hope that [ellisonleao/gruvbox.nvim](https://github.com/ellisonleao/gruvbox.nvim) can achieve the same effect.

ellisonleao/gruvbox.nvim:
![image](https://user-images.githubusercontent.com/102474041/221498971-863696ef-3baf-46e4-9a3f-590ec35f2fde.png)

gruvbox-baby:
![image](https://user-images.githubusercontent.com/102474041/221499022-38dec9b6-650a-4c7d-831d-2d418bfab4b5.png)

@ellisonleao have some plan for this?
