### ISSUE TITLE
Can this be installed with vim plug?

### ISSUE THREAD

**Issue by rew1nter** [ellisonleao/gruvbox.nvim#200]

**Comment by ellisonleao** [comment]
hey @rew1nter , yes

```vim
Plug 'ellisonleao/gruvbox.nvim'

lua EOF <<<
require('gruvbox').setup()
EOF

" then setting background and colorscheme as usual in vimscript
```

**Comment by rew1nter** [comment]
I don't write lua. I'm using the init.vim file to customize nvim. In this case, Is it enough to just put `Plug 'ellisonleao/gruvbox.nvim'` in the plugins section?

**Comment by rew1nter** [comment]
Well, I just tried and it seems to be working. The color scheme makes the terminal non-transparent tho. Let me know if you know of any way to keep the terminal transparent while using a selected color scheme
