### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by rajat1saxena** [ellisonleao/gruvbox.nvim#202]
After applying the theme using the instructions provided on the landing page, I got the following colorscheme. It does not look OK. I am a Neovim newbie so please guide me if anything is missing from my setup.

**Screenshots**
<img width="1077" alt="Screenshot 2023-02-03 at 1 38 14 PM" src="https://user-images.githubusercontent.com/821092/216546232-12d2c12b-7893-4253-a5ac-22fc74faafe6.png">

**Comment by ellisonleao** [comment]
hey @rajat1saxena can you share your config and the neovim version you are using please?

**Comment by ellisonleao** [comment]
closing since we don't have an answer. Feel free to reopen
