### ISSUE TITLE
Displaying of listchar with cursorline stopped working with commit 925b496

### ISSUE THREAD

**Issue by cryptomilk** [ellisonleao/gruvbox.nvim#203]
**Describe the bug**
Displaying of listchar with cursorline stopped working with 925b496cc02ddd7942b31a105413afd73b74bd69

**To Reproduce**
1. Create a file with tabs
2. `:set lcs=tab:>-,trail:-`
3. `:set list`
4. `:set cursorline`

**Expected behavior**
Display listchars when cursorline is active.

**Screenshots**

Working e.g. with commit e863942494d7c72a7c8d2c54cf651f28fc5a76ab
![gruvbox_working_c64ec557672c9c8ecc71a438533525482021377f](https://user-images.githubusercontent.com/545480/217311379-e83055e4-2b7e-4150-9de0-51569bc6d7eb.png)

Breaks with commit 925b496cc02ddd7942b31a105413afd73b74bd69
![gruvbox_broken_925b496cc02ddd7942b31a105413afd73b74bd69](https://user-images.githubusercontent.com/545480/217311456-56acfef1-99b7-4e78-be48-f63334a5a55a.png)

**Comment by cryptomilk** [comment]
@Defman21 FYI

**Comment by Defman21** [comment]
`ayu` uses the `IndentBlanklineContextChar` highlight group, I'm going to give it a try.

https://github.com/Shatur/neovim-ayu/blob/master/lua/ayu/init.lua#L201

**Comment by Defman21** [comment]
btw I'm not able to reproduce it for some reason.

I've changed the `Whitespace` group to `{ fg = colors.red }` and I've applied your `:set`'s and this is how it looks for me:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/7100645/217776692-ad242391-99ff-4123-a2bb-67fc490a59b5.png">

```
NVIM v0.9.0-dev-869+g964ae205a
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by cryptomilk** [comment]
It works with `fg = colors.red` but not with `fg = colors.bg1`! I guess `colors.bg1` is also used for the cursorline ...

**Comment by cryptomilk** [comment]
`Whitespace = { fg = colors.bg2 }` works ...
