### ISSUE TITLE
Original color will be cleared when overriding a attribute

### ISSUE THREAD

**Issue by Hanaasagi** [ellisonleao/gruvbox.nvim#205]
**Describe the bug**
Hello, I want to make diagnostic virtual text italic， so I override them in `setup` function,  but it doesn't work.

I have tried only overriding the `italic` attribute, but the original color is lost. Please take a look at the first two diagnostic messages; they are italicized but not colored. Then I attempted to set a color, but it's not italicized. You can see the `DiagnosticVirtualTextError`.

![2023-02-09_23-30](https://user-images.githubusercontent.com/9482395/217858400-9f973d48-db58-43bc-b06f-1f840ad4d374.png)

**To Reproduce**
Minimal Reproducible Code

```Lua
require("gruvbox").setup({
    overrides = {
        String = { italic = false },
        DiagnosticVirtualTextError = { link = "GruvboxRed", italic = true },
        DiagnosticVirtualTextWarn = { italic = true },
        DiagnosticVirtualTextInfo = { italic = true },
        DiagnosticVirtualTextHint = { italic = true },
    },
})
 
```

**Expected behavior**

Italic and not changed color.

Thanks.

**Comment by Hanaasagi** [comment]
After some searching, I know that `link` has high priority. Other attribute will not work when `link` exists.


https://github.com/ellisonleao/gruvbox.nvim/blob/b9d23a64dc8f22b4af8fa708d9fcbffbbf5747c6/lua/gruvbox/groups.lua#L787-L792

A solution: get attributes from `link` and assgin to table.

```Lua
  for group, hl in pairs(config.overrides) do
    local link = nil
    if groups[group] and not vim.tbl_isempty(hl) then
      link = groups[group].link
      groups[group].link = nil
    end
    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl, groups[link] or {})
  end

```

**Comment by ellisonleao** [comment]
@Hanaasagi good catch! Are you able to provide a PR to fix this? It would be nice to have tests for that too. What do you think?

**Comment by Hanaasagi** [comment]
Please take a look #207

**Comment by Hanaasagi** [comment]
@ellisonleao  Hi, I found the color info is lost again after recently update. May I ask why the fix is reverted in https://github.com/ellisonleao/gruvbox.nvim/pull/226. Thanks
