### ISSUE TITLE
[Question] Is it intentional the GruvboxBg groups are setting the fg color?

### ISSUE THREAD

**Issue by EdJoJob** [ellisonleao/gruvbox.nvim#213]
Looking at the `lua/gruvbox/groups.lua:37-41`, the `GruvboxBg` groups are changing the foreground color, not the background color.

I was expecting that a hlgroup named as `GruvboxBgX` would be manipulating the background color, not the foreground color from the name.

**Comment by ellisonleao** [comment]
@EdJoJob yep, it's the same convention we have in the [vimscript version](https://github.com/gruvbox-community/gruvbox/blob/master/colors/gruvbox.vim#L518-L522), which this plugin was referenced by
