### ISSUE TITLE
Better JSX colors like https://github.com/luisiacc/gruvbox-baby

### ISSUE THREAD

**Issue by Tyangs** [ellisonleao/gruvbox.nvim#214]
[gruvbox-baby](https://github.com/luisiacc/gruvbox-baby) has good support for treesitter jsx. I really hope that [ellisonleao/gruvbox.nvim](https://github.com/ellisonleao/gruvbox.nvim) can achieve the same effect.

ellisonleao/gruvbox.nvim:
![image](https://user-images.githubusercontent.com/102474041/221498971-863696ef-3baf-46e4-9a3f-590ec35f2fde.png)

gruvbox-baby:
![image](https://user-images.githubusercontent.com/102474041/221499022-38dec9b6-650a-4c7d-831d-2d418bfab4b5.png)

@ellisonleao have some plan for this?

**Comment by ellisonleao** [comment]
hey, @Tyangs thanks for the suggestion. Honestly, I don't mess too much with .tsx files so both options seem to work fine. If more people are interested in this, we can think about it but for now, we are cool. Feel free to open a new Discussion and see what the others think about it.

**Comment by Tyangs** [comment]
ok, thanks for your reply
