### ISSUE TITLE
Telescope border override isn't applying correctly

### ISSUE THREAD

**Issue by datsfilipe** [ellisonleao/gruvbox.nvim#223]
**Describe the bug**: I have Telescope border foreground defined in *overrides* section inside theme setup. But when it starts, instead of the foreground color I'd defined, it has the value of `GruvboxFg1`.

1. In overrides section, I have this:
```lua
TelescopeResultsBorder = { fg = '#504945', bg = 'NONE' },
TelescopePromptBorder = { fg = '#504945', bg = 'NONE' },
TelescopePreviewBorder = { fg = '#504945', bg = 'NONE' },
```
2. When starting neovim with the config it doesn't have the color applied;
3. Looking in highlights with the command `Telescope highlights` it shows that the borders have the value of `GruvboxFg1`

I'm using `Lazy` as plugin manager, it is configured as recommended for the theme. I tried making Telescope plugin load after or before but didn't worked.

**Comment by ellisonleao** [comment]
@datsfilipe i've just pushed a PR to attempt to fix the issue. Are you able to validate it on your side please?

**Comment by datsfilipe** [comment]
@ellisonleao yes, it worked for me with your PR commit.
