### ISSUE TITLE
After neovim 9.0 update the colors went crazy

### ISSUE THREAD

**Issue by Arisa-Snowbell** [ellisonleao/gruvbox.nvim#237]
**Describe the bug**
Colors went bad, idk it just looks weird, i can't find logical sense in it, it's all blending together, i can't by color recognize what is what

**To Reproduce**
1. Install ellisonleao/gruvbox.nvim
2. Install lsp_config
3. Setup rust analyzer
4. Update to neovim 9.0

**Expected behavior**
To colors to be identical to previous version or somehow at least to make logical sense as for their colors, now it's all just blending together

**Screenshots**
Neovim 8.3
![image](https://user-images.githubusercontent.com/22961592/230790126-8e91aba3-e89d-4c39-be8a-b183ec78410b.png)
Neovim 9.0
![image](https://user-images.githubusercontent.com/22961592/230790176-f1dce064-6d11-4635-b4b2-19882de212a2.png)

**Comment by darkangel-ua** [comment]
It's `semantic highlighting` enabled by default in 0.9. You can disable it to get back to `treesitter` variant.

**Comment by Arisa-Snowbell** [comment]
By the :Inspect command it seems semantic highlighting default in neovim is able to way better know which is which thing but it uses all these colors for so many things, tree sitter doesn't recognize a lot of components and such, could that be fixed so it works with neovim default semantic highlighting nicer? by the inspect command I can see the colors can be changed specifically for rust for these components

**Comment by polyzen** [comment]
Already merged: https://github.com/ellisonleao/gruvbox.nvim/pull/211

**Comment by Arisa-Snowbell** [comment]
Then It doesn't work very well :| 

So then I guess I am forced to use a different theme, I am kinda sad now, I really liked this one
I think the only way to fix it is from this theme, the colors come from this theme but it just has bad settings for it
tree-sitter just isn't as good as neovim's semantic highlighting, neovim's default semantic highlighting gives more info

gruvbox-material works perfectly okay it just doesn't have the color pallet I like, which is the pallet this theme uses
gruvbox-material is too blend

:cry:

**Comment by ellisonleao** [comment]
I am happy to add the new highlights in another PR, seems like we can grab an example https://github.com/sainnhe/gruvbox-material/blob/master/colors/gruvbox-material.vim#L713-L736

**Comment by Arisa-Snowbell** [comment]
That would be really nice, thank you, @ellisonleao
