### ISSUE TITLE
Add new semantic tokens highlight groups

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/gruvbox.nvim#241]
ref: https://github.com/sainnhe/gruvbox-material/blob/master/colors/gruvbox-material.vim#L713-L736

**Comment by eeeXun** [comment]
Found in this [PR](https://github.com/neovim/neovim/pull/22022)
[The following groups are linked by default to standard |group-name|s:](https://github.com/neovim/neovim/blob/master/runtime/doc/lsp.txt#L549-L563)
```
    @lsp.type.class         Structure
    @lsp.type.decorator     Function
    @lsp.type.enum          Structure
    @lsp.type.enumMember    Constant
    @lsp.type.function      Function
    @lsp.type.interface     Structure
    @lsp.type.macro         Macro
    @lsp.type.method        Function
    @lsp.type.namespace     Structure
    @lsp.type.parameter     Identifier
    @lsp.type.property      Identifier
    @lsp.type.struct        Structure
    @lsp.type.type          Type
    @lsp.type.typeParameter TypeDef
    @lsp.type.variable      Identifier
```

We can 
1. link to treesitter
2. change the `standard` group color
3. create new one for lsp
