### ISSUE TITLE
Broken signature highlight for Noice

### ISSUE THREAD

**Issue by sQVe** [ellisonleao/gruvbox.nvim#246]
**Describe the bug**
Since e685aebb5967c2597858a41779a8d38321253509 the highlights for the signature help that https://github.com/folke/noice.nvim provides is borken.

**To Reproduce**
1. Install https://github.com/folke/noice.nvim
2. Trigger signature help

**Expected behavior**
The highlights should be clear and easy to read.

![image](https://user-images.githubusercontent.com/2284724/232778261-6ac25016-1bfa-42cd-8678-7a7180f45066.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/2284724/232778430-31a0aa27-a4a0-4254-b6fe-d85ab6542d8c.png)

**Comment by eeeXun** [comment]
This is cause by https://github.com/ellisonleao/gruvbox.nvim/pull/243/files#diff-55d08b53de540100df87c946fd5f6f085fc842e6b73aa78a451f9e60d0414f11R198. The `@error` links to `Error`, which would reverse text color.
Remove it in https://github.com/ellisonleao/gruvbox.nvim/pull/245.

And also, in https://github.com/ellisonleao/gruvbox.nvim/pull/234, I link `LspSignatureActiveParameter` to `Search`. I think this is clear to read.
![image](https://user-images.githubusercontent.com/58657914/232788630-5e5f6431-8c72-41e2-92b4-4665a3a8b5e0.png)

**Comment by sQVe** [comment]
Yeah, works now with the latest release 👍🏼
