### ISSUE TITLE
Add color magenta

### ISSUE THREAD

**Issue by cryptomilk** [ellisonleao/gruvbox.nvim#250]
I think it would be nice to have an additional color.

`color.magenta = '#de5285'`

![gruvbox+magenta](https://user-images.githubusercontent.com/545480/233084482-3f52a800-f124-4615-97d8-a82e010f73db.png)

What do you think?

**Comment by ellisonleao** [comment]
IMO this is more like a personal preference since the current pink color (`#d3869b` and its variants) can suit just fine. If you feel that should be an important topic, please open a discussion.
