### ISSUE TITLE
[feat] Add configuration to enable/disable term colors

### ISSUE THREAD

**Issue by protiumx** [ellisonleao/gruvbox.nvim#259]
**Is your feature request related to a problem? Please describe.**
I'd like the terminal colors inside neovim to keep the colors of my terminal rather than being changed to gruvbox colors.

**Describe the solution you'd like**
A new configuration entry like `enable_term_colors` should suffice.

**Describe alternatives you've considered**

**Additional context**

**Comment by ellisonleao** [comment]
this honestly feels like an edge case which I am not considering supporting right now
