### ISSUE TITLE
Diffs in neogit not as expected

### ISSUE THREAD

**Issue by TimothyPescatore** [ellisonleao/gruvbox.nvim#269]
**Describe the bug**
Since a while the background colors of a git diff in neogit cover the whole diff.
Therefore the text is either not visible at all or just barely.
Problem only occurred since a while, unfortunately I can't remember since when,
so I don't know if it was a gruvbox update or a neogit update.

**To Reproduce**
Install neogit and see a diff of a modified file.
Keep/Set "inverse" to true
I tried my config with custom setting and without and I deleted the whole plugin
several times.

**Expected behavior**
Diff colors are at least like in the diffview.nvim view or even better as in 
https://github.com/ellisonleao/gruvbox.nvim/pull/225
(I don't know why this commit was reverted...)

**Screenshots**
Neogit diff view when cursor is off the modified file
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/79797643/2ab8a84c-2d19-45fb-9afe-6da5beb87a71)

Neogit diff view when cursor is on deleted part
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/79797643/2f41c71b-75d5-4ede-b573-fa0e1c8cc20c)

Neogit diff view when cursor is on the file name
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/79797643/7d775636-1be3-4dfb-8327-d64ba03b3147)

Neogit diff view with inverse false
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/79797643/6d6c4f6e-05ac-4964-894e-44168e88d859)

Same file viewed in diffview.nvim
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/79797643/d64978b7-ce41-459b-af17-518858c956f7)

**Additional context**

**Comment by ellisonleao** [comment]
hey @TimothyPescatore unfortunately i don't have too much time to work on this right now but there's a discussion ongoing about diffs [here](https://github.com/ellisonleao/gruvbox.nvim/discussions/239).  Since neovim introduced semantic highlights in the newer versions, we will need to check what's the best way to handle this issue

**Comment by ellisonleao** [comment]
moving this to the discussion
