### ISSUE TITLE
DiffText is too similar to Search

### ISSUE THREAD

**Issue by asheq-svmx** [ellisonleao/gruvbox.nvim#273]
**Is your feature request related to a problem? Please describe.**
DiffText looks exact same as Search which can get really confusing

**Describe the solution you'd like**
Want DiffText highlight to be changed. I think it should be markedly different from other common highlights like Search. May be to something purple-y or blue-y.

**Describe alternatives you've considered**
I am able to override in my config to an (ugly) purple that I chose myself. But I would like someone with a professional eye to choose a color and benefit the entire user base.

**Additional context**
Here's the problem in a diff (invoked by git fugitive):
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/54650582/bb38121a-303a-4101-a6e6-75ec6841b3fe)

- The DiffText highlight is surrounding the `vf` (I added spacing around it).
- The Search higlight is `sf` (I search for `sf` using `/`)

Notice how it is super confusing at first glance because you don't know which is which without thinking and checking.

**Comment by ellisonleao** [comment]
moving this to the [diff discussion](https://github.com/ellisonleao/gruvbox.nvim/discussions/239)
