### ISSUE TITLE
Doesn't look good with Neogit

### ISSUE THREAD

**Issue by brglng** [ellisonleao/gruvbox.nvim#275]
**Describe the bug**
Some colors are broken under Neogit

**To Reproduce**
1. `colorscheme gruvbox`
2. `:Neogit`

**Expected behavior**
The text color in the diff chunks should be distinguished from the background color.

**Screenshots**
![2023-09-22 18-04-55 的屏幕截图](https://github.com/ellisonleao/gruvbox.nvim/assets/115389762/1fa2532c-d31a-4bd5-bf67-247ff515f943)

**Additional context**

**Comment by zdcthomas** [comment]
I'm seeing the same thing

**Comment by DrunkenToast** [comment]
Any progress on this issue? It is kind of a shame that this colorscheme doesn't properly support git diff colors.

**Comment by ellisonleao** [comment]
moving the issue to the discussion https://github.com/ellisonleao/gruvbox.nvim/discussions/239
