### ISSUE TITLE
`vim.cmd.hi("clear")` not conditional after updating

### ISSUE THREAD

**Issue by GllmR** [ellisonleao/gruvbox.nvim#277]
**Describe the bug**
Latest version remove conditional `vim.cmd.hi("clear")` 

**To Reproduce**

Set some `vim.cmd('hi "something"')` then call `colorscheme gruvbox`

**Expected behavior**
Clearing highlights should be conditional so i can customize colors THEN apply gruvbox theme.

**Comment by ellisonleao** [comment]
hey @GllmR can you clarify a little bit more why is that a problem? how are you customizing the colors?
