### ISSUE TITLE
Recent changes break highlights from other sources

### ISSUE THREAD

**Issue by notEvil** [ellisonleao/gruvbox.nvim#279]
Hi,

I recently tried [coc.nvim](https://github.com/neoclide/coc.nvim) and saw highlights disappear after updating gruvbox. The issue is that

https://github.com/ellisonleao/gruvbox.nvim/blob/08a551cc8140e6ca41b5de6cabf75d02a246c330/lua/gruvbox/init.lua#L83

was previously conditional on `vim.g.colors_name`. It can be fixed by executing `colorscheme gruvbox` within `init=function() ... end` when using `lazy.nvim`.

**Comment by notEvil** [comment]
```lua
require('lazy').setup({
...
  {
    'neoclide/coc.nvim',
    branch='release',
    build=':CocInstall coc-pyright',
  },
...
  {
    'ellisonleao/gruvbox.nvim',
    priority=1000,
    init=function() vim.cmd([[colorscheme gruvbox]]) end,
  },
...
})

...

-- vim.cmd([[colorscheme gruvbox]])
```
and a few hl links in a FileType autocmd (disabled while testing)

**Comment by ellisonleao** [comment]
@notEvil thanks. Can you explain a little bit more what are the highlights with issues? Are those from Coc itself or Gruvbox? Can you try to inspect some of them using the `:Inspect` command and see what are the outputs please?

**Comment by notEvil** [comment]
![](https://github.com/ellisonleao/gruvbox.nvim/assets/4567628/9a112558-043f-437e-a2bb-88d33b9f465c)

top before
bottom after moving `colorscheme gruvbox` to `init`

Don't think you need to investigate any further. The change in https://github.com/ellisonleao/gruvbox.nvim/commit/a749759e66341696a08f5e1bc572b4ccb121281b obviously clears the highlights on `colorscheme gruvbox` that coc sets up earlier.

**Comment by ellisonleao** [comment]
I see, will rollback that change until i figure out another way

**Comment by ellisonleao** [comment]
done in https://github.com/ellisonleao/gruvbox.nvim/commit/65f2b9e3b554c4579129e393d76044068ab34eed
