### ISSUE TITLE
debugPC highlight broken

### ISSUE THREAD

**Issue by potamides** [ellisonleao/gruvbox.nvim#283]
**Describe the bug**
`debugPC` is defined like this:
```lua
debugPC = { bg = colors.faded_blue },
```
But colors.faded_blue is a `nil` value.

**To Reproduce**
```
:hi debugPC
```

**Comment by potamides** [comment]
Thank you for addressing this so quickly! But now debugPC is linked to lightblue whereas previously it was linked to darkblue. This can cause some issues since lightblue is also used for syntax highlighting. Consider this:

![2023-10-07-140321_450x43_scrot](https://github.com/ellisonleao/gruvbox.nvim/assets/53401822/8984fdfa-fbaf-4715-9062-7e3688ec23c0)

Versus this:

![2023-10-07-140343_351x39_scrot](https://github.com/ellisonleao/gruvbox.nvim/assets/53401822/8c0d7f0c-4252-4589-9285-42b9006d8bf3)

**Comment by ellisonleao** [comment]
hey @potamides thanks for raising that. Are you using treesitter with lsp semantic highlights?

**Comment by potamides** [comment]
No,  I am using regex based syntax highlighting.

**Comment by eeeXun** [comment]
nvim-dap use the [`debugPC` for `DapStopped` highlight](https://github.com/mfussenegger/nvim-dap/blob/92dc531eea2c9a3ef504a5c8ac0decd1fa59a6a3/lua/dap.lua#L252). The c0369bf case the text unreadable while using nvim-dap.

![image](https://github.com/ellisonleao/gruvbox.nvim/assets/58657914/81bfa130-5f4d-4c33-ad79-474d14f7ef89)
