### ISSUE TITLE
[Question] How to enable red undercurl for SpellBad?

### ISSUE THREAD

**Issue by poperigby** [ellisonleao/gruvbox.nvim#285]
Sorry if this is a dumb question, but I'm having a lot of trouble with this. I'm trying to make the `SpellBad` highlight group have a red undercurl. 

I tried:

```lua
overrides = {
    BadSpell = { undercurl = true, sp = "#fb4934" }
}
```

Then I opened a new document, and typed some gibberish, and `:set spell`, but the incorrectly spelled word was underlined in white.

**Comment by ellisonleao** [comment]
hey @poperigby, no problem, the override should be:

```lua
overrides = {
    SpellBad = {undercurl = true, sp = "#fb4934"}
}
```

**Comment by poperigby** [comment]
Thank you! It looks like I hadn't set WezTerm as my `TERM`, so that was why it wasn't working.
