### ISSUE TITLE
`DiffAdd` is grey

### ISSUE THREAD

**Issue by ambroisie** [ellisonleao/gruvbox.nvim#290]
**Describe the bug**
After updating the plug-in, the color of `DiffAdd` changed from green to grey.

**To Reproduce**
1. Use `git commit` with `commit.verbose=true` configured.
2. Notice that the wrong color is being used.

**Expected behavior**
I would expect it to be green, as it used to be.

**Screenshots**
![Screenshot](https://github.com/ellisonleao/gruvbox.nvim/assets/12465195/6cacd6c2-f81a-4afe-ba94-938681e66402)
![`:highlight`](https://github.com/ellisonleao/gruvbox.nvim/assets/12465195/eb546968-6a9b-469c-9d2a-689b943ac499)

**Additional context**
I'm not sure _why_ it changed, as looking at the code/`:highlight` everything looks in order. I don't override any color in my config either.

**Comment by ambroisie** [comment]
This seems to be related to `tmux`, as running `nvim` outside of `tmux` shows the correct colors (though more muted than I rembered).

![image](https://github.com/ellisonleao/gruvbox.nvim/assets/12465195/6f8744e4-e7bb-4f74-88fd-b72328f2aaa1)
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/12465195/ddf48ef6-c4bc-4ee7-9d41-f7934627115f)

**Comment by ambroisie** [comment]
Here is how it looked before:

In `tmux`:
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/12465195/f965308f-12b5-40ac-a144-e852070eacb2)

Outside of `tmux`:
![image](https://github.com/ellisonleao/gruvbox.nvim/assets/12465195/61375afe-f89e-4bcd-a950-233b48b1603e)

This is with `tmux 3.3a` in all screenshots.

**Comment by ambroisie** [comment]
The change in look seems to be from d3b86c23e0fbbcd338900241ca55f3cef1da6111 and related to #239. I will be looking into how to reverse the change, as I dislike the more muted look.

I will leave the bug open, as I think this might be an issue for other people, even if I work around it through going back to the previous style.

**Comment by mrvon** [comment]
Agree, Old style more confortable and clear to me, I use tag to revert it right now.
```
Plug 'ellisonleao/gruvbox.nvim', {'tag': '5e697fa640944dd4a98748d15c6e0a7725777551'}
```

**Comment by ambroisie** [comment]
Alright, so I fixed the `tmux`/native terminal issue: turns out my `tmux` was not correctly configured for 24-bit colour!

See [this SO answer](https://stackoverflow.com/a/41786092).

I still dislike the new styling however, so thankfully #291 gets us _most_ of the way there (not quite: I want _both_ the old colours and the low-key high-lighting from `reverse = true`).

**Comment by ellisonleao** [comment]
hey guys, thanks for opening the issue. I've made a comment in the PR so i really think this should be changed using overrides in your config. LMK if that work for you guys
