### ISSUE TITLE
Comment out conditionally compiled code (C/C++) if inactive

### ISSUE THREAD

**Issue by nysal** [ellisonleao/gruvbox.nvim#300]
**Describe the bug**
C/C++ have preprocessor directives for conditionally compiling code. It will be nice to comment out inactive code blocks

**To Reproduce**
1. The screenshots posted below are from the Linux kernel code, but any C/C++ code with the following preprocessor directives should exhibit the issue
```
#define __BLOCK1 1

#ifdef __BLOCK1
// Code block 1
#else
// Code block 2
#endif
```

**Expected behavior**
`// Code block 2` should be commented out

**Screenshots**
Ran `:Inspect` and took screenshots of gruvbox and tokyonight color schemes:
![1gb](https://github.com/ellisonleao/gruvbox.nvim/assets/8509287/0ea93635-f130-4684-9633-e39b1f5cb85a)

The `#else` block is inactive and commented out
![1tn](https://github.com/ellisonleao/gruvbox.nvim/assets/8509287/fa303397-6eef-4a10-b7a2-70a7f64b7eb2)

**Additional context**
The following patch helps, but it does inherit the `italic` from the `Comment` style, which seems reasonable to me.

```diff
@@ -1023,7 +1023,7 @@ local function get_groups()
     ["@macro"] = { link = "Macro" },
     ["@structure"] = { link = "Structure" },
     ["@lsp.type.class"] = { link = "@type" },
-    ["@lsp.type.comment"] = {}, -- do not overwrite comments
+    ["@lsp.type.comment"] = { link = "@comment" },
     ["@lsp.type.decorator"] = { link = "@macro" },
     ["@lsp.type.enum"] = { link = "@type" },
     ["@lsp.type.enumMember"] = { link = "@constant" },
```

**Comment by ellisonleao** [comment]
hey @nysal thanks for the issue. Can you open a PR please?
