### ISSUE TITLE
GitSigns use wrong background color

### ISSUE THREAD

**Issue by hanschen** [ellisonleao/gruvbox.nvim#304]
**Describe the bug**
I'm not sure if this is intentional or not, but to me it seems like `GitSignsAdd` etc. use the wrong background color because they link to `GruvboxGreen` etc.

https://github.com/ellisonleao/gruvbox.nvim/blob/0940564208a490c173216c3b7d2188b0a5ad3491/lua/gruvbox.lua#L400-L402

It looks as expected if I use `GruvboxGreenSign` etc. instead (with the default settings and ` transparent_mode = false`).

**Comment by miguelbarao** [comment]
I think those lines lines should be set as

```lua
    GitSignsAdd ={ fg = colors.green, bg = colors.bg1 },
    GitSignsChange = { fg = colors.aqua, bg = colors.bg1 },
    GitSignsDelete = { fg = colors.red, bg = colors.bg1 },
```

**Comment by miguelbarao** [comment]
As a workaround, I use this configuration in lazy:

```lua
  {
    'ellisonleao/gruvbox.nvim',
    enabled = true,
    event = 'VeryLazy',
    keys = { '<F54>', '<Cmd>colorscheme gruvbox', desc = 'Gruvbox (colorscheme)' },
    priority = 1000,     -- load before the other start plugins
    opts = {
      contrast = 'soft', -- 'hard', '', 'soft'
      dim_inactive = true,
      overrides = {
        NormalFloat = { bg = '#32302f' }, -- FIXME: make floating windows discernible when dim_inactive
        GitSignsAdd = { link = "GruvboxGreenSign" },
        GitSignsChange = { link = "GruvboxOrangeSign" },
        GitSignsDelete = { link = "GruvboxRedSign" },
      },
    },
```

**Comment by kanna5** [comment]
These changes were introduced in 9fb8fce2f3b81321c76dbbf562aeffb1abd2c0bd and I think this was intentional.

I'm currently using this override in my config to make it look better:

```lua
SignColumn = { link = "LineNr" }
```

**Comment by hanschen** [comment]
> These changes were introduced in [9fb8fce](https://github.com/ellisonleao/gruvbox.nvim/commit/9fb8fce2f3b81321c76dbbf562aeffb1abd2c0bd) and I think this was intentional.

Thanks, that makes sense. I'll close this issue assuming that it's indeed intentional (it's easy enough to work around using `overrides`).

**Comment by miguelbarao** [comment]
Please don't close it, using `overrides` is not a solution.

**Comment by hanschen** [comment]
If you read the comment in the linked commit, @ellisonleao said:

> But answering your question, the main point of the change was to remove the BG of that highlight which is the way other colors themes are using it

So it does seem like an intentional choice. I'll leave it to @ellisonleao to re-open the issue if he considers it to be a bug.
