### ISSUE TITLE
Background looks inconsistent in some parts

### ISSUE THREAD

**Issue by diegoulloao** [ellisonleao/gruvbox.nvim#305]
**Describe the bug**
Sometimes the background looks inconsistent, it happens when I open nvim-tree or the cmd float input.
Only happening with gruvbox.

**To Reproduce**
Using almost the basic configuration
```lua
-- set dark background
vim.opt.background = "dark"

gruvbox.setup({
  italic = {
    strings = false,
  },
  contrast = "", -- options: soft|hard|empty
})

-- set colorscheme
vim.cmd([[ colorscheme gruvbox ]])
```

**Expected behavior**
See background color working good in all cases, even when plugins like nvim-tree are opened.

**Screenshots**

https://github.com/ellisonleao/gruvbox.nvim/assets/45423661/318674d0-f951-4df6-ac0e-0b75c9a008f9

**Additional context**
```
nvim version: 0.9.4
os: macOs Sonoma 14.1
terminal: iTerm2 build 3.4.22
```

**Comment by ellisonleao** [comment]
hey @diegoulloao unfortunately some plugins use custom background colors and not links for their colors. We need to understand first which color group they are using for the background and they match our one. Makes sense?

**Comment by diegoulloao** [comment]
I understand. I fixed some of them by overwriting the groups, Idk if the best solution, but works.

**Comment by diegoulloao** [comment]
I leave some of the groups that I overwrote, could be useful for someone:

```lua
-- fix
-- git signs column bg
vim.cmd([[ hi! SignColumn guibg=NONE ]])

-- fix
-- winbar bg
vim.cmd([[ hi! WinBar guibg=NONE ]])
vim.cmd([[ hi! WinBarNC guibg=NONE ]])

-- fix
-- noice cmd line bg
vim.cmd([[ hi! NoiceCmdlinePopup guibg=#282828 ]])
vim.cmd([[ hi! NoiceCmdlinePopupBorder guibg=#282828 ]])

-- fix
-- telescope selection bg
vim.cmd([[ hi! TelescopeSelection guibg=#3c3836 guifg=#fe8019 gui=bold ]])

-- fix
-- diagnostics sign bg
vim.cmd([[ hi! DiagnosticSignOk guifg=#b8bb26 guibg=#282828 ]])
vim.cmd([[ hi! DiagnosticSignInfo guifg=#83a598 guibg=#282828 ]])
vim.cmd([[ hi! DiagnosticSignWarn guifg=#fabd2f guibg=#282828 ]])
vim.cmd([[ hi! DiagnosticSignError guifg=#fb4934 guibg=#282828 ]])

-- fix
-- lsp saga bg
vim.cmd([[ hi! SagaNormal guibg=#282828 ]])
```
