### ISSUE TITLE
Upcoming TS highlight group changes

### ISSUE THREAD

**Issue by ObserverOfTime** [ellisonleao/gruvbox.nvim#310]
TS captures will soon be changed and colorschemes will need to be updated.
This is a heads-up to prevent #159 from reoccurring.
See nvim-treesitter/nvim-treesitter#4799 for more details.

**Comment by ObserverOfTime** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/5895/commits/8b7a32ad12d1b3ff9a927c38295c8ee8d55aec18 will be merged soon.

**Comment by roland-5** [comment]
@ellisonleao this will be breaking too https://github.com/neovim/neovim/pull/27067

**Comment by JulesNP** [comment]
I've submitted a pull request (https://github.com/ellisonleao/gruvbox.nvim/pull/315) to resolve https://github.com/nvim-treesitter/nvim-treesitter/commit/3f978f85b55330217bceec53dd54cf33f3541076

**Comment by h3ndry** [comment]
is this part of what is being discuss here ? [https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/](https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/)

**Comment by Mathijs-Bakker** [comment]
> is this part of what is being discuss here ? https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/

Affirmative

**Comment by JulesNP** [comment]
I'm not sure, as I don't normally work with LaTex. Is your issue with LaTex highlighting something which only started happening after the recent treesitter update?

If you're using lazy.nvim package manager, you can quickly test if my pull request fixes it by changing your plugin config to this:
```lua
{
    "JulesNP/gruvbox.nvim",
    branch = "tsfix",
}
```

**Comment by ellisonleao** [comment]
can we close this one @ObserverOfTime ?
