### ISSUE TITLE
[FEATURE] Material color palette

### ISSUE THREAD

**Issue by dot-1q** [ellisonleao/gruvbox.nvim#330]
### Is your feature request related to a problem? Please describe.

After experimenting with various gruvbox themes for Neovim, none comes close to this one in terms of compatibility and plugin support.
The only problem I face, is that I really liked the [gruvbox-material](https://github.com/sainnhe/gruvbox-material) color palette, and after experimenting with the palette overrides, i could only come very close on dark mode, but not nail it quite right in light mode. Plus, there's differences in light and dark mode in the material palette for the various colors, which could not be achieved. 

### Describe the solution you'd like

The same way there's `hard` and `soft` variants to the colors, I think this would be the easier way to implement a _material_ variant also, which we could choose from in the options menu.
[Light and dark variants](https://imgur.com/a/j4U9wOL) with palette override.

```
palette_overrides = {
          dark0 = '#282828',
          dark1 = '#3c3836',
          dark2 = '#504945',
          dark3 = '#665c54',
          dark4 = '#7c6f64',
          light0 = '#fbf1c7',
          light1 = '#f4e8be',
          light2 = '#f2e5bc',
          light3 = '#eee0b7',
          light4 = '#e5d5ad',
          bright_red = '#ea6962',
          bright_green = '#a9b665',
          bright_yellow = '#d8a657',
          bright_blue = '#7daea3',
          bright_purple = '#d3869b',
          bright_aqua = '#89b482',
          bright_orange = '#e78a4e',
          neutral_red = '#cc241d',
          neutral_green = '#98971a',
          neutral_yellow = '#d79921',
          neutral_blue = '#458588',
          neutral_purple = '#b16286',
          neutral_aqua = '#689d6a',
          neutral_orange = '#d65d0e',
          dark_red = '#722529',
          dark_green = '#62693e',
          dark_aqua = '#49503b',
          gray = '#928374',
          faded_red = '#c14a4a',
          faded_green = '#6c782e',
          faded_yellow = '#647109',
          faded_blue = '#45707a',
          faded_purple = '#945e80',
          faded_aqua = '#4c7a5d',
          faded_orange = "#c35e0a",
          light_red = "#ae5858",
          light_green = "#ebeabc",
          light_aqua = "#dee2b6",
        }
```

**Comment by olivertzeng** [comment]
@dot-1q I'm also a gruvbox-material lover/user
there are [this](https://github.com/wittyjudge/gruvbox-material.nvim) and [this](https://github.com/sainnhe/gruvbox-material)
however the former doesn't work when the window is too small and the latter isn't written in lua. hope that the material colorscheme will be implemented in this project.

**Comment by ellisonleao** [comment]
hey @dot-1q thanks for the suggestions, however I don't have plans to make this available. you can always override the color palettes to use your personal preference, or just stick with @olivertzeng suggestion and use the already awesome gruvbox-material colorscheme
