### ISSUE TITLE
[BUG] Colors of parenthesis in neovim 0.10.0 is pure white instead of themed

### ISSUE THREAD

**Issue by DavidTelenko** [ellisonleao/gruvbox.nvim#335]
### Describe the bug

In nvim 0.10 due to changes introduced to highlight groups (apparently) colors of parenthesis and commas, has pure white color instead of themed.

### Expected behaviour

Colors of parenthesis should match colors of brackets.

### Screenshots

# nvim 0.10.0
![nvim 0.10.0](https://github.com/ellisonleao/gruvbox.nvim/assets/63603558/371937dc-fa62-4481-84a1-d3f7e38daf51)
# nvim 0.9.5
![nvim.0.9.5](https://github.com/ellisonleao/gruvbox.nvim/assets/63603558/7bee4f66-08fc-4d42-af4e-8ad8ba56247d)

**Comment by dssste** [comment]
Add `vim.api.nvim_set_hl(0, 'Delimiter', { link = 'GruvboxOrange' })` after the `vim.cmd('colorscheme gruvbox')` could be a workaround before this getting fixed

**Comment by DavidTelenko** [comment]
Thanks @dssste

**Comment by lorenzolfm** [comment]
> Adding `vim.api.nvim_set_hl(0, 'Delimiter', { link = 'GruvboxOrange' })` after the `vim.cmd('colorscheme gruvbox')` could be a temporary workaround.

didn't work for me
