### ISSUE TITLE
[BUG] Update gruvbox and vsplit color is bright white (neovim 10)

### ISSUE THREAD

**Issue by SamSaffron** [ellisonleao/gruvbox.nvim#338]
### Describe the bug

 Somehow something changed and now vsplit is bright white, which is a bit blinding. 

I suspect this is a neovim 0.10  cause it was just updated

### Expected behaviour

be less blinding. 

### Screenshots

![image](https://github.com/ellisonleao/gruvbox.nvim/assets/5213/8152e23a-5454-4179-80cf-4a9d5fa01c78)

**Comment by xudyang1** [comment]
Try `:highlight WinSeparator` or `:highlight VertSplit` to see any unexpected highlight.

Neovim v0.10 has some [breaking changes](https://neovim.io/doc/user/news-0.10.html#_-breaking-changes) in highlight groups:

- `hl-WinSeparator is linked to hl-Normal instead of hl-VertSplit.`

**Comment by SamSaffron** [comment]
omg ...no idea what I did (I removed gruvbox temporarily) and now it all seems to be working correctly again.

Sorry for the noise here.
