### ISSUE TITLE
[BUG] Markdown Inline code blocks / latex expressions not highlighted correctly

### ISSUE THREAD

**Issue by gmmyung** [ellisonleao/gruvbox.nvim#353]
### Describe the bug

Using the TS `markdown_inline` parser should highlight inline codeblock / math, but gruvbox.nvim currently does not.

### Expected behaviour

It should highlight those.

### Screenshots

![Screenshot from 2024-07-10 22-12-14](https://github.com/ellisonleao/gruvbox.nvim/assets/25163944/91f162f3-d72a-40f2-993b-fafcc6289e3d)

**Comment by ellisonleao** [comment]
hey @gmmyung do you have the expected output? can you provide the `:Inspect` result for this block?

**Comment by gmmyung** [comment]
<img width="1280" alt="image" src="https://github.com/ellisonleao/gruvbox.nvim/assets/25163944/4bf73af9-0321-4287-bc88-c11f1db88013">
<img width="2560" alt="image" src="https://github.com/ellisonleao/gruvbox.nvim/assets/25163944/d627ad9b-a1c6-480e-96d6-c132fbe7fa63">
https://github.com/nvim-treesitter/nvim-treesitter/issues/5397
It should work like this in theory.

**Comment by gmmyung** [comment]
Sorry, my bad. I had TS highlighting disabled in my setup. Thanks again for your awesome library!
