### ISSUE TITLE
[FEATURE] Add support for noice cmdline popup

### ISSUE THREAD

**Issue by tungstengmd** [ellisonleao/gruvbox.nvim#354]
### Is your feature request related to a problem? Please describe.

when i'm typing in cmdline with noice the bg looks odd with the background

### Describe the solution you'd like

a solution would prolly be to just support the plugin

**Comment by ellisonleao** [comment]
hey @tungstengmd PRs are welcome! can you open one please?

**Comment by eugene-babichenko** [comment]
Opened a PR just for that! https://github.com/ellisonleao/gruvbox.nvim/pull/361

**Comment by tungstengmd** [comment]
closing when the pr is merged.

**Comment by tungstengmd** [comment]
thx now i can die happy <3
