### ISSUE TITLE
[FEATURE] New tagged release

### ISSUE THREAD

**Issue by Anrock** [ellisonleao/gruvbox.nvim#360]
### Is your feature request related to a problem? Please describe.

Last release 2.0.0 is lagging behind master pretty hard, cut a new one?

### Describe the solution you'd like

New release is created and I can point my plugin manager to it instead of random commit

**Comment by ellisonleao** [comment]
hey @Anrock! yep we are just waiting to push more issues before bumping that. Thanks!
