### ISSUE TITLE
[BUG] fzf-lua unreadable white highlights on light mode

### ISSUE THREAD

**Issue by cwlbraa** [ellisonleao/gruvbox.nvim#373]
### Describe the bug

happy to hear if I'm reporting this in the wrong spot, but recently switched to fzf-lua and on light mode the filenames are highlighted white and are therefore unreadable. I don't know if this is better addressed as "feature: fzf-lua support" or if some fallback white could be replaced with a more high-contrast option.

contrast is fine on dark mode, fwiw.

### Expected behaviour

on light mode, the filenames should be legible against the beige background.

### Screenshots
"colorscheme.lua" isn't legible here.
![Screenshot 2024-12-16 at 10 03 32 AM](https://github.com/user-attachments/assets/0ee935a1-354d-440f-9f0c-c57a3c2a6a5e)

**Comment by cwlbraa** [comment]
after some digging, this might be related to @none? is that something the theme should set to black or near-black when it's in bg-light mode?

**Comment by cwlbraa** [comment]
tokyonight-day seems to provide a non-white color for `@none`, making this highlight fine. not sure exactly how they do that, though, [the code doesn't appear to do anything special](https://github.com/search?q=repo%3Afolke%2Ftokyonight.nvim%20%40none&type=code).

![Screenshot 2024-12-17 at 1 34 48 PM](https://github.com/user-attachments/assets/13ab131a-92af-4080-90bf-2a0d16a6b8f9)

**Comment by cwlbraa** [comment]
worked this out with the fzf-lua maintainer. feel free to close!

**Comment by ellisonleao** [comment]
hey @cwlbraa can you share what was your fix please? maybe we need to improve the highlights on our side as well

**Comment by cwlbraa** [comment]
It's unclear to me if there's a trick to make the theme accommodate this better, @ibhagwan might be able to speculate.

they explain here:
https://github.com/ibhagwan/fzf-lua/issues/1576#issuecomment-2550007892

**Comment by ibhagwan** [comment]
The issue was setting fzf colors, setting a bg+ color without fg+ which apparently doesn’t inherit from fg, so adding a fallback to Normal solved the issue.

The issue wasn’t/isn’t with the color scheme.
