### ISSUE TITLE
Everything after #if or #ifdef gets bold and and underlined in C

### ISSUE THREAD

**Issue by cryptomilk** [ellisonleao/gruvbox.nvim#57]
As soon as an `#if` or `#ifdef` comes in the code, treesitter is making everything bold and underlined with gruvbox theme:

![neovim-treesitter-hightlighting](https://user-images.githubusercontent.com/545480/125280897-df978680-e315-11eb-95af-854627725167.png)

The C code is here:
https://git.samba.org/?p=samba.git;a=blob;f=source4/kdc/mit-kdb/kdb_samba_policies.c;h=9197551ed6198dd28ba3b9b39797926aeff2cf8c;hb=refs/heads/master#l290

**To Reproduce**

1. Install nvim-treesitter and enable highlighting.
2. Install and use gruvbox.nvim colorscheme
3. Open C code with some `#ifdef` e.g. https://git.samba.org/?p=samba.git;a=blob;f=source4/kdc/mit-kdb/kdb_samba_policies.c;h=9197551ed6198dd28ba3b9b39797926aeff2cf8c;hb=refs/heads/master#l290

**Expected behavior**

Do not underline or make text bold as soon as the #if clause is over.

The issue doesn't happen with another colorscheme.

**Comment by Mechap** [comment]
I have the same problem in c++ with try/catch

**Comment by cryptomilk** [comment]
It could also be a treesitter issue ...

```c
#include <stdio.h>

int main(void)
{
    /* This is commented out */
#if 0
    {
    This is commented out too
#endif
    return 0;
}
```

**Comment by cryptomilk** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/1632

**Comment by ellisonleao** [comment]
closing this since it's unrelated to the plugin
