### ISSUE TITLE
startify colorscheme weird

### ISSUE THREAD

**Issue by chipsenkbeil** [ellisonleao/gruvbox.nvim#58]
I've been porting all of my configs over to Lua from vimscript and was previously using the primary [`gruvbox`](https://github.com/morhetz/gruvbox) plugin, which produced this color layout:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/2481802/126079873-9a15d42d-278b-405d-81fa-ae2b9199b4cb.png">

Now, when switching to this plugin as part of my overall process, the colors appear odd:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/2481802/126079881-bd88f318-936f-457f-a9f9-40079c6be2aa.png">

I've got some other plugins going on like [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter), but I added startify to the exclusion list and it didn't seem to do anything; so, not sure what I'm missing. Maybe there's some dependency order conflict?

**Comment by chipsenkbeil** [comment]
Also, I tested by commenting out this plugin and adding back in the original repo and the color schemes work just fine.

<img width="988" alt="image" src="https://user-images.githubusercontent.com/2481802/126080011-25607f6e-87bf-403b-8744-79363b38dfca.png">

**Comment by ellisonleao** [comment]
Are you using treesitter?

**Comment by chipsenkbeil** [comment]
> Are you using treesitter?

Yeah, I am
