### ISSUE TITLE
Feature Request: Markdown code block highlighting

### ISSUE THREAD

**Issue by zpyg** [ellisonleao/gruvbox.nvim#64]
Just like vscode
![图片](https://user-images.githubusercontent.com/63000762/130886793-7f40dcc7-d52a-47f0-accb-444485ed5186.png)

**Comment by ellisonleao** [comment]
Not sure if this fits here. This could be probably handled by treesitter if you have markdown parser for it, but I am not sure how far that parser is handling the colors for code blocks.  Do you know how vscode handles the color inside code blocks? Is it another plugin?

**Comment by zpyg** [comment]
@ellisonleao It's a build-in feature of vscode. But I found that there is [a vim plugin](https://github.com/plasticboy/vim-markdown) that can do this.

**Comment by misaflo** [comment]
You can configure the [default plugin](https://github.com/tpope/vim-markdown) (include in neovim), in your init.lua:
```lua
vim.g.markdown_fenced_languages = {'c'}
```

**Comment by zpyg** [comment]
> 
Thank you, it worked!
