### ISSUE TITLE
Make the colorscheme without requiring lush

### ISSUE THREAD

**Issue by ashincoder** [ellisonleao/gruvbox.nvim#66]
Hi, I have loved this lua port very much. One think I would love to is to stop requiring lush for the colorscheme and making it a indenpendent lua port colorscheme. Was this topic ever been in your mind ?. Other than that I love it very much. 
Thank you for your work. Have a nice day :smile:

**Comment by ellisonleao** [comment]
Oh yeah, this is definitely in the plan!

**Comment by ellisonleao** [comment]
lush dependency is now removed, thanks to @mhdahmad !
