### ISSUE TITLE
Bland and little color variation for R syntax (.r files)

### ISSUE THREAD

**Issue by joiharalds** [ellisonleao/gruvbox.nvim#67]
The gruvbox colorscheme displays bland colored syntax highlighting for the R language, .r files, compared to other colorschemes like the default colorscheme.

I have Treesitter set up and working as can be seen in the images, using Treesitter playground.

With default colorscheme syntax highlighting looks proper:

![Screenshot from 2021-09-14 15-55-48](https://user-images.githubusercontent.com/14778057/133292595-0fa7b03c-020e-4ad4-8708-5fc06a3b5eb7.png)

With gruvbox colorscheme the syntax highlighting looks bland, e.g. operators not colored and functions bold but not colored:
![Screenshot from 2021-09-14 15-55-56](https://user-images.githubusercontent.com/14778057/133292823-9d6e4356-25cd-4553-a6a6-4569a2784e5e.png)

The gruvbox colorscheme is applied and works it seems, I just find it lacking compared to the syntax highlighting of other languages with gruvbox. Minimal init.vim file used for images: https://pastebin.com/AZQmRnmz

Is this how gruvbox is designed for R or is there something wrong with my setup? If this is just the way it is, can I specify a different gruvbox colorscheme only for .r files and if that's possible could someone point me in the right direction in doing so?

**Comment by ellisonleao** [comment]
hey @joiharalds not sure if this is an issue with the proper R treesitter support. Unfortunately i am not much of a help for this particular one since i don't use R. Have you checked if https://github.com/arnau/vim-rlang maybe can help improve some of the groups?

**Comment by joiharalds** [comment]
Thanks for the answer!
I'm already using Nvim-R which supersedes vim-R-Plugin which vim-rlang is extracted from.

My lazy solution is to just use a different colorscheme for .R files. I could probably amend the colors of gruvbox for .R files but haven't gotten around to it. I'll report here if I do something of that sort.
