### ISSUE TITLE
Undefined function lightline#update

### ISSUE THREAD

**Issue by Mange** [ellisonleao/gruvbox.nvim#70]
Starting up neovim with `colorscheme gruvbox` shows an error:

```
Error executing vim.schedule lua callback: Vim:E117: Unknown function: lightline#disable
```

I tried debugging this, but it has a super weird behavior. The error comes from this part:

```lua
  local has_lightline, _ = pcall(vim.fn["lightline#update"])
  if has_lightline then
    local ll_filled = vim.fn['lightline#colorscheme#fill'](lightline_theme)
    vim.g['lightline#colorscheme#gruvbox#palette'] = ll_filled
    vim.schedule(function()
      vim.fn['lightline#disable']()
      vim.fn['lightline#enable']()
    end)
  end
```

If I comment out the `vim.schedule(…)` call then I get no error. I also do not get the error if I manually invoke `:colorscheme gruvbox` after startup.

I do not have `lightline` installed and the `lightline#update` function is not defined after startup. But it seems like it is defined shortly between the code loading and the first scheduled callbacks executing.

Adding `print` calls does not help; it seems like this code is run twice where the first run is never actually logged.

I grepped all my installed plugins for `lightline#update` and this is the only match. I don't understand what could cause this, honestly. Perhaps `vim.fn` is in a weird state during startup…?

```
> nvim --version
NVIM v0.6.0-dev+390-g3beea1fe1
```

**Comment by Mange** [comment]
(Ha ha, we changed titles as the same time.)

**Comment by ellisonleao** [comment]
Fixed in https://github.com/ellisonleao/gruvbox.nvim/commit/d00787254c5417dda002c94028bdf6b0079bd3e9
