### ISSUE TITLE
Q: Visual selection inverted colors are looking strange. Everything OK here?

### ISSUE THREAD

**Issue by VKondakoff** [ellisonleao/gruvbox.nvim#72]
Hi!

Here is how visual selection colors are looking on my machine:
<img width="701" alt="Снимок экрана 2021-10-15 в 14 54 18" src="https://user-images.githubusercontent.com/230824/137493098-16d3b0b3-28bf-44b1-bcf2-4c83eccc6ef2.png">
<img width="698" alt="Снимок экрана 2021-10-15 в 15 17 15" src="https://user-images.githubusercontent.com/230824/137493129-5a0632b0-1260-4b38-9946-57eb0da1333b.png">

Is this expected behavior or there is smth wrong with my setup?
Thanks!

**Comment by ellisonleao** [comment]
hey @VKondakoff can you share your current config please?

**Comment by VKondakoff** [comment]
Thanks for looking into this!

Here is a minimal config:
```lua
vim.o.termguicolors = true

require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use { "ellisonleao/gruvbox.nvim", requires = { "rktjmp/lush.nvim" } }
end)

vim.o.background = "light" -- or "light" for light mode
vim.g.gruvbox_contrast_dark = "soft"
vim.g.gruvbox_contrast_light = "soft"
vim.cmd([[colorscheme gruvbox]])
```
Screenshot:
<img width="677" alt="Снимок экрана 2021-11-09 в 18 38 46" src="https://user-images.githubusercontent.com/230824/140956203-1741f983-0960-4b6b-96ac-72706b462ec1.png">

And here is how it looks if I add `list`/`listchars` options:
```lua
vim.o.list = true
vim.o.listchars = 'tab:→ ,space:·,nbsp:␣,trail:•,eol:¶,precedes:«,extends:»'
```
<img width="677" alt="Снимок экрана 2021-11-09 в 18 41 56" src="https://user-images.githubusercontent.com/230824/140956416-720305fc-5106-432c-aa5c-e3ef0e26ae21.png">

**Comment by ellisonleao** [comment]
ok i will take a look asap and let you know.
