### ISSUE TITLE
Using lightline, the neovim welcome screen flickers out

### ISSUE THREAD

**Issue by perrin4869** [ellisonleao/gruvbox.nvim#77]
This is a minor annoyance, but `disable`/`enable` lightline causes the welcome screen to flicker out almost instantly after booting vim.

**Comment by ellisonleao** [comment]
not sure how to fix that behaviour, feel free to open a PR if you find any fixes!

**Comment by perrin4869** [comment]
Maybe the issue should remain open? I tried to look into it a while back but I couldn't figure it out either
