### ISSUE TITLE
Feature request: transparent background

### ISSUE THREAD

**Issue by begss** [ellisonleao/gruvbox.nvim#78]
Original gruvbox had `gruvbox_transparent_bg` option for that.

**Comment by sQVe** [comment]
This is, as far as I know and according to the readme, already supported. All options of the original gruvbox is.

**Comment by begss** [comment]
Well, I just got that I saw this option in https://github.com/morhetz/gruvbox/pull/287, not in gruvbox itself. However, it's pretty useful as it's the only way to do transparent background, because any "`highlight <...>`" commands in init.lua doesn't take effect.

**Comment by gmr458** [comment]
Try this and it doesn't work, it would be great to have this feature or if it's already added why doesn't it work? Am I doing something wrong?
![image](https://user-images.githubusercontent.com/53343401/142788478-de9fe918-2762-4b6b-9dc6-63a3b2d66ccb.png)

**Comment by begss** [comment]
> Try this and it doesn't work, it would be great to have this feature or if it's already added why doesn't it work? Am I doing something wrong? ![image](https://user-images.githubusercontent.com/53343401/142788478-de9fe918-2762-4b6b-9dc6-63a3b2d66ccb.png)

My PR isn't merged yet, so for solution on line 82 to work you'll have to apply my patch manually or to clone my PR's branch. Line 86 doesn't work at all, and that's the reason why I did this PR.

**Comment by ellisonleao** [comment]
Sorry guys, the original repo and the community version on which this repo is based does not have that option so I would recommend for you guys that still want that behaviour to add the config manually in your configs.

**Comment by timsofteng** [comment]
> Try this and it doesn't work, it would be great to have this feature or if it's already added why doesn't it work? Am I doing something wrong?
> ![image](https://user-images.githubusercontent.com/53343401/142788478-de9fe918-2762-4b6b-9dc6-63a3b2d66ccb.png)

Hello. How did you achieve this italic font rendering?

**Comment by gmr458** [comment]
@timsofteng Font Dank Mono Regular and Italic

**Comment by timsofteng** [comment]
> @timsofteng Font Dank Mono Regular and Italic

I mean how to force `gruvbox.nvim` to display italic in cases as on your screenshot?
My main font is `source code pro` and I have full bundle including italic mono one. But in same case it render regular mono.

@ellisonleao 
Maybe you have ideas?

And I still don't understand how to enable transparent background.

**Comment by gmr458** [comment]
@timsofteng find all options that have "italic" in the name with Ctrl+f in the browser. https://github.com/morhetz/gruvbox/wiki/Configuration
