### ISSUE TITLE
Plugin does not work if you dont have lightline installed

### ISSUE THREAD

**Issue by dortin42** [ellisonleao/gruvbox.nvim#82]
![image](https://user-images.githubusercontent.com/20261354/143723813-5637e0ee-01d0-45bb-989b-1655263d6d78.png)

NeoVim 0.6

**Comment by ellisonleao** [comment]
hey @dortin42 can you show some configs? The strange thing is that this error is being raised after the first lightline check, which in this case was successful. Can you share some configs so i can try to reproduce on my side please? I am not getting any errors here

**Comment by tracyone** [comment]
@ellisonleao @dortin42 try my pr

**Comment by dortin42** [comment]
@ellisonleao sorry for late response on this, no, when the plugin failed I removed it, rn I'm using another theme, anyway, I didn't do any weird config for this, just installed, failed and reported here

**Comment by ellisonleao** [comment]
Fixed in https://github.com/ellisonleao/gruvbox.nvim/commit/d00787254c5417dda002c94028bdf6b0079bd3e9
