### ISSUE TITLE
CursorLineNr not coloring for neovim 0.6

### ISSUE THREAD

**Issue by eeeXun** [ellisonleao/gruvbox.nvim#86]
When `set relativenumber`, the number will be highlight for the line of cursor.
After upgrade to neovim 0.6, it doesn't work.

### neovim 0.5
![](https://i.imgur.com/jaM6RUy.png)

### neovim 0.6
![](https://i.imgur.com/NmCZDjY.png)

**Comment by stvhuang** [comment]
It works for me with NeoVim `v0.6.0-dev+637-gafbf89dc0`.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15218222/144733621-6297ed10-167b-4886-8bcf-3068d9cf70c1.png">

**Comment by eeeXun** [comment]
version:
![image](https://user-images.githubusercontent.com/58657914/144734209-3a28156c-283e-47fc-87fb-09c7d2dca439.png)

**Comment by eeeXun** [comment]
May be the change in neovim
## 0.5
![image](https://user-images.githubusercontent.com/58657914/145513389-ac0d6fa1-74b0-4a28-9556-d732b9047dac.png)
## 0.6
![image](https://user-images.githubusercontent.com/58657914/145513481-94d272b5-136e-404e-9eb9-a9966165bd07.png)
