### ISSUE TITLE
Problem setting theme

### ISSUE THREAD

**Issue by franciscomunozz** [ellisonleao/gruvbox.nvim#98]
I have installed gruvbox on nvim, but at the time to setting it to the color scheme, my nvim looks like this:

![image](https://user-images.githubusercontent.com/77551844/149597129-6551b6b1-c55e-4529-9c12-f4bcfdcf6012.png)
(Is installed)
![image](https://user-images.githubusercontent.com/77551844/149597138-79c66c76-db54-416c-9a4c-0435ef9fb999.png)
 
I'm on windows and my neovim version is the v0.6.1

**Comment by DrShongos** [comment]
add `set termguicolors` before setting the colorscheme.

**Comment by ellisonleao** [comment]
I believe @DrShongos has answered it for you.
